### PR TITLE
Fixed wrong type for MmGlobalData kernel export

### PR DESCRIPTION
**Pull request by ergo720**
Triggered by this [PR](https://github.com/XboxDev/nxdk/pull/560) in nxdk.

### CODE REVIEW

**Comment by PatrickvL** [comment]
Is something planning to tie the memory manager to these fields?

**Comment by ergo720** [comment]
No, and it can't be done for most of them since the internal implementation details of our memory manager differ than what the xbox kernel would do. For example, there's no Vad tree and so we can't set the Vad variables of the global.

**Comment by PatrickvL** [comment]
Some homebrew or other software might read these fields and make decisions based on them, so for these cases populating the relevant fields might improve accuracy

**Comment by ergo720** [comment]
The new changes in the memory manager files are simply because I had to add the `xbox::` prefix everywhere because the mm type declarations have been moved inside the xbox namespace, nothing changed code-logic wise.

**Review by RadWolfie — APPROVED** [review]

**Pull request merged**
