### PR TITLE
Implement STOS, Inline OutputDebugStringA & Fix Vertex Declaration oversight

### PR DESCRIPTION
**Pull request by LukeUsher**
This *may* fix some of the recent regressions after the d3d-tweaks PR was merged...
Please make sure to test before merged

### CODE REVIEW

**Comment by PatrickvL** [comment]
LGTM - awaiting a few test reports before merging....

**Comment by LukeUsher** [comment]
Confirmed to fix crash/ early fatal error regression in Sonic Heroes, GTA: San Andreas and a few others,

**Comment by LukeUsher** [comment]
With this PR, for the first time ever: Colin McRae Rally 3 doesn't crash when changing the camera angle/view

**Comment by PatrickvL** [comment]
With regards to the regressions mentioned in #1458, @gandalfthewhite19890404 reports on this PR:

> NFS MW BE create vertex declaration was fixed

**Comment by ObiKKa** [comment]
Oh, swell. These are good changes. Can you please state what STOS stands for to us laymen? And a brief explanation of what it does, if you don't mind?

**Comment by LukeUsher** [comment]
@LukeUsher STOS is an X86 instruction, see https://c9x.me/x86/html/file_module_x86_id_306.html

**Comment by gandalfthewhite19890404** [comment]
MK is not hangs, need just to wait

**Comment by AzurikRiseOfPerathia** [comment]
Other

**Pull request merged**
