### PR TITLE
merged ALIAS OOVPA with multiple patterns into one

### PR DESCRIPTION
**Pull request by jarupxx**
Remove as much ALIAS OOVPA as possible #323 
One of the work of be merged multiple patterns into one.

### CODE REVIEW

**Comment by LukeUsher** [comment]
Good work but that's a lot of changes. Can you tell us what you have done for regression testing?

**Comment by jarupxx** [comment]
After completing work, we conducted a regression test with the following titles. All titles passed test.

Azurik - Rise of Perathia (3911)
Halo (3925)
Jet Set Radio Future (4134)
Smashing Drive (4242)
Crash Bandicoot - Wrath of Cortex (4361)
Buffy the Vampire Slayer (4432)
Crazy taxi 3 (4531)
Turok - Evolution (4627)
Quantum Redshift (4721)
Namco Museum (4831)
Shikigami no Shiro Evolution - Red (5028)
Otogi (5120)
All-Star Baseball 2004 (5233)
Starsky And Hutch (5344)
Star Wars - Knights of the Old Republic (5455)
Battlestar Galactica (5558)
Dance Dance Revolution Ultramix (5659)
All-Star Baseball 2005 (5788)
Puyo Pop Fever (5849)

**Comment by LukeUsher** [comment]
I'm satisfied with that, thanks and good work!

**Comment by PatrickvL** [comment]
Great work!!!

**Pull request merged**
