### PR TITLE
Fix no input issue for certain titles.

### PR DESCRIPTION
**Pull request by jackchentwkh**
Fix no input issues for titles like RalliSport and others. 
test result needed.
I keep the JSRF hack this time. So this minor modification is only to fix those no input titles.

### CODE REVIEW

**Comment by jackchentwkh** [comment]
frankly speaking, I think the dwPacketNumber update could be the main thing for fixing the no input issue.

**Comment by jackchentwkh** [comment]
These titles progress from no input to normal input:
RalliSportChallenge
RalliSportChallenge Demo
Party Blast

There titles show regressions:
None

**Comment by jarupxx** [comment]
Could it be that no respond input yet by Directinput?
Unfortunately, RalliSport is still no respond input.

**Comment by jackchentwkh** [comment]
sorry, this fix is only for Xinput. The dwPacketNumber must be updated every polling cycle. 
I will check the direct input later for an possible fix.

**Comment by gandalfthewhite19890404** [comment]
Please anyone - test LEGO Star Wars, it suffers from no-input-issue. I can't test it myself - away from home.
Thanks!

**Comment by jackchentwkh** [comment]
the newly added emulated dwPacketNumber fixed direct input (keyboard) in RalliSport Challenge.
I can proceed to create a new profile and choose a Race. After starting the Race, title crashed. but that's new progress.

**Pull request merged**
