### PR TITLE
NV2A expansion

### PR DESCRIPTION
**Pull request by PatrickvL**
Better to start work on NV2A with all available symbols, improvements and tweaks

### CODE REVIEW

**Comment by x1nixmzeng** [comment]
Neat! Glad your branch is finally seeing the light of day!

**Comment by PatrickvL** [comment]
Thanks, but this part wasn't the reason my WIP branch was capable to go further. (That had to do with less HLE patching, using D3D global state variables, generic render state conversions, centralised texture conversion and other stuff - Luke is redoing that now in his experimental branch, in smaller steps with similar results)

**Comment by PatrickvL** [comment]
The NV2A should be emulated at low level, that's what this work is slowly preparing for.
We've got enough resources now to get it further, it just takes time. (Resources like pbkit, openxdk, nxdk, xqemu, OpenXbox, mame and other Nvidia chipsets emulated)

**Comment by ObiKKa** [comment]
Patrick, to your second comment up above, has Luke been reading/checking your WIP branch before starting on his version work?

3rd comment: That's an awful work of research and work!

**Comment by LukeUsher** [comment]
@ObiKKa I refer to it at time to time, but my work mostly an independent implementation based on my own research and findings. What is great is we both came to the same conclusions and hit similar problems in the process, so we must be on the right track ;)

**Comment by PatrickvL** [comment]
Also, remember that Radwolfie already copied over most, if not all, of the non-rendering code changes from my WIP branch. This includes my OOVPA extensions, hidden behind an ifdef

**Comment by RadWolfie** [comment]
@PatrickvL 😛 Yup, since some of the references are not declared or functional at the time back then in master branch.

It is supposedly for preparation to have WIP_LessVertexPatching branch with DXD8 relative files readily available re-port on top of master branch.

**Pull request merged**
