### PR TITLE
Upscale rendertargets and depth surfaces consistently

### PR DESCRIPTION
**Pull request by NZJenkins**
Rather than just upscaling the backbuffer
Allows high resolution rendering in some games that rendered to textures
Fixes Amped shadows when upscaling, due to SetRenderTarget failure (probably mixing scaled and unscaled RT & Depth)

Games that wouldn't upscale properly before:
* Panzer Dragoon Orta
* Crash Tag Team Racing
* Crash Nitro Kart (menu only)

### CODE REVIEW

**Review by LukeUsher — APPROVED** [review]

**Comment by ESPPIRAL** [comment]
Knight of the Temple 2

Master
Cxbx-Reloaded 37195a6 (Mar 13 2021) _ Emulating TM-019 v1 01 (Knights of the Temple 2) 20_03_2021 9_26_00


PR (gorgeous)
Cxbx-Reloaded 9607b68 (Mar 19 2021) _ Emulating TM-019 v1 01 (Knights of the Temple 2) 20_03_2021 9_27_06

**Comment by ESPPIRAL** [comment]
Dead Or Alive 3

Master
Cxbx-Reloaded 37195a6 (Mar 13 2021) _ Emulating MS-045 v1 01 (Dead or Alive 3) 20_03_2021 9_43_30


PR (reflections are now upscaled)
Cxbx-Reloaded 9607b68 (Mar 19 2021) _ Emulating MS-045 v1 01 (Dead or Alive 3) 20_03_2021 9_44_53

**Comment by ESPPIRAL** [comment]
Virtua Cop 3 

Master
Cxbx-Reloaded 37195a6 (Mar 13 2021) _ Emulating 00000000 v1 00 (Virtua Cop 3) 20_03_2021 9_56_11 (2)

PR
Cxbx-Reloaded 9607b68 (Mar 19 2021) _ Emulating 00000000 v1 00 (Virtua Cop 3) 20_03_2021 9_52_53

**Comment by ESPPIRAL** [comment]
Shadow of memories also renders to a texture and it upscales properly.

MASTER
Cxbx-Reloaded 37195a6 (Mar 13 2021) _ Emulating KN-014 v1 01 (Shadow of Memories) 20_03_2021 10_17_59

PR
Cxbx-Reloaded 9607b68 (Mar 19 2021) _ Emulating KN-014 v1 01 (Shadow of Memories) 20_03_2021 10_16_50

**Comment by vanderleivieirainacio** [comment]
Unfortunately, AMD cards do not have these improvements. In fact, some games look like this: 
Captura de tela 2021-03-20 141021
Captura de tela 2021-03-20 141048
Captura de tela 2021-03-20 141021
Captura de tela 2021-03-20 141048
My video card is an AMD Radeon RX 580 4GB

**Comment by vanderleivieirainacio** [comment]
Yes, this problem has existed for a long time in the master version and in PR on AMD cards.

**Comment by vanderleivieirainacio** [comment]
Just to be clear, it is not the fault of this update but a problem that has existed for a long time on AMD cards. Maybe you need an investigation to find out why this happens.

**Comment by ergo720** [comment]
> Maybe you need an investigation to find out why this happens.

We probably know already: cxbxr is currently using vertex shader model 3.0 with pixel shader model 2.a or pixel fixed function pipeline, and this likely breaks AMD rendering. The temporary solution for end users is to press F2 while playing or to use a graphics wrapper such as dxvk for the time being. This will probably be properly fixed when the emulator moves to D3D10 or D3D11.

**Comment by vanderleivieirainacio** [comment]
Thanks, it worked for some games by pressing F2. I just don't know how to use DXVK on Windows but I appreciate it, they helped me a lot! The good thing will be the migration to DirectX 10 or 11, in the future. But I have a question, will there be DirectX 12?

**Comment by ergo720** [comment]
Please join our discord server [here](https://discord.com/invite/26Xjx23) to ask this kind of questions, since Github is not a forum for end users but a place for developers to build software. The short answer to your question is that there are no plans at the moment for a future D3D12 port.

**Pull request merged**
