### PR TITLE
Removed all mentions of cxbe 

### PR DESCRIPTION
**Pull request by BenNottelling**
Don't merge this yet, I uploaded files to a folder were they don't need it to be and need to remove them.
I Removed all mentions of cxbe in every .h and .cpp file. Tested and verified to compile and still emulate. Also, I made a new "about" image with gimp. The project file is "About.xcf", I only made it because it's more relevant to Cxbx Reloaded. Use it if you wish :D

### CODE REVIEW

**Comment by PatrickvL** [comment]
Conflicts can be resolved by just removing the files.

**Comment by PatrickvL** [comment]
As for the new About image - regardless of it's quality, that shouldn't be mixed in with the other commits.

**Comment by BenNottelling** [comment]
@PatrickvL I'll swap it out with the original and update the other sources to resolve the conflicts.

**Comment by PatrickvL** [comment]
It's better to revert commit 6f44c10

**Comment by BenNottelling** [comment]
@PatrickvL I already replaced it

**Comment by BenNottelling** [comment]
@PatrickvL If I give you editorial permission for my fork can you remove the files? I don't have any time today to do it myself as i go straight from school to work.

**Comment by PatrickvL** [comment]
I've got no time for that, sorry

**Comment by BenNottelling** [comment]
@PatrickvL I've finally found the time to remove those files so it should be good to merge now

**Comment by LukeUsher** [comment]
Thanks for the effort, but I'm not sure about merging this one. We could squash the commits together but I'm not sure that's the right thing to do here.

Let's wait for somebody else to chime in but I'm sorry, my gut feeling is to reject this pull-request.

If that does happen, you're very welcome to try again, submitting only the removal of Cxbe references in a single commit

**Comment by PatrickvL** [comment]
I've skimmed over the changes; Apart from the actual removal of Cxbe mentions, it seems polluted with some of the other changes done when merging the CxbxKrnl.DLL into the Cxbx.exe. This is probably due to the steep learning curve of how to work with git (I haven't grokked it either).

**Comment by LukeUsher** [comment]
Due to the aforementioned issues (pollution from non-related changes & the messy commits) I'm going to close this pull request.

As I said earlier, you're welcome to try again, and if you do, make sure to only make a single commit containing only the Cxbx removal changes

**Pull request closed without merging**
