### PR TITLE
Introduce XAPI database v2

### PR DESCRIPTION
**Pull request by jarupxx**
Source:
Azurik - Rise of Perathia (3911)
NightCaster (4039)
Double-S.T.E.A.L (4134)
Flight Academy (4361)
Turok - Evolution (4627)
Quantum Redshift (4721)
NBA 2K3 (4831)
Shikigami no Shiro Evolution (5028)
Cyber Attack Team (5233)
Starsky And Hutch 5344 (5344)
XIII (5558)
Steel Battalion - Line of Contact (5788)
Forza Motorsport (5849)

### CODE REVIEW

**Comment by RadWolfie** [comment]
I'll check this PR some time after 10 hours from now. Unless other dev team member has the time to verify it and merge it.

**Comment by RadWolfie** [comment]
The introduction part looks good to me by the way.

**Comment by PatrickvL** [comment]
I'm away from keyboard this weekend, so I'm afraid you'll have to excuse me... Nice work though!

**Comment by RadWolfie** [comment]
Only thing I noticed between each titles is it add XAutoPowerDownResetTimer to HLE cache file. I went ahead check the OOVPA to be sure if it is a strong offset/value in it. Turns out it is weak.

At offset 9:
`B8 00 90 65 B5     mov         eax,0B5659000h`

It has offset 0x0A included however it did not include the whole assembly line code which is unique.

Plus so is offset 0:
`6A CD              push        0FFFFFFCDh`

By implement both unique assembly lines code in XAutoPowerDownResetTimer shall make the OOVPA strengthen for less false detection. Plus it is generic OOVPA. I'll correct it, then merge into the branch.

**Comment by RadWolfie** [comment]
Correction: I'll fix XAutoPowerDownResetTimer's OOVPA after the merge.

Turns out nothing has changed within OOVPA revisions in this PR. Just adding to V2 database support. I'll go ahead merge it.

**Comment by RadWolfie** [comment]
UPDATE: Regression has occur with [4242] Gauntlet: Dark Legacy title for missing functions below.
```
XID_fCloseDevice=10fbc2
XInputClose=10f1ef
XInputGetCapabilities=10f1fb
XInputGetState=10f3d8
XInputOpen=10f199
XInputSetState=10f447
```

Solution: Lower OOVPA revision to include support for 4242 titles.

**Pull request merged**
