### PR TITLE
DSound improvements (alternative volume heuristics)

### PR DESCRIPTION
**Pull request by CookiePLMonster**
PR mutually exclusive to #1991, submitted so people can test and pick which sounds better.

Brings the same changes as the other PR, but with different heuristics for picking the buffer volume - this PR picks the maximum channel volume from all speakers (except for the LFE speaker).

Since the current code picks a single volume level for all channels, it will never be perfect - but those two PRs exist so we can test which of the two approaches provides better volume levels.

### CODE REVIEW

**Comment by LanHikariDS** [comment]
This PR does not fix the volume issue for sound effects in Jedi Outcast, unfortunately

**Comment by RadWolfie** [comment]
I am currently in favor of get this pull request merge since it is more logical than the other one. Plus what I had seen in several titles do have several channels involve center channel mixbin volume.

@literalmente-game Had you made any tests with this pull request for any regression/improvement?

**Comment by literalmente-game** [comment]
Couldn't find any difference in all games I've checked (around 20 games). Burnout engine sound it's _probably_ slightly higher with this change, but nothing very noticeable

**Review by RadWolfie — APPROVED** [review]

**Comment by gandalfthewhite19890404** [comment]
Black is completely silent with this PR.

**Comment by PatrickvL** [comment]
@CookiePLMonster stated that this PR causes a regression : Main menu BGM is gone in The Warriors

**Pull request merged**
