### PR TITLE
Thread safe FS processing using spinlock

### PR DESCRIPTION
**Pull request by LukeUsher**
Addresses issue #986.

This will probably have no noticeable improvement, but could improve stability in some cases.

### CODE REVIEW

**Comment by LukeUsher** [comment]
Minimal risk, so merging.

**Comment by gandalfthewhite19890404** [comment]
Tested twice - this PR cause hang in 2002 World Cup! 
Need to revert and investigate.

**Comment by LukeUsher** [comment]
This caused a regression (crash) in Sims 2
Likely a value of a register changes unintended.

Will investigate after work

**Comment by RadWolfie** [comment]
>Likely a value of a register changes unintended.

The solution is to use **`pushad`** before custom code and **`popad`** after the custom code. This allow to preserve register values. However, you will need outside variable to set during custom code. Then set outside variable to one of the register after custom code.

In some environment, **`pushfd`** and **`popfd`** might be require to prevent override EFLAGS register.

**Comment by LukeUsher** [comment]
Yeah, I'm aware, I looked into it already. I'm not sure why I made a second custom spinlock implementation, I already made a better one as part of a previous experiment. I'll update shortly

**Comment by gandalfthewhite19890404** [comment]
This PR cause hang in Prince of Persia Sands of Time. I checked non-merged reverting PR, its good.
<details><summary>PR1345:</summary>
image
</details>
<details><summary>PR1346 (revert):</summary>
image
</details>
I think - need revert #1345, #1355 and complete rework it with BIG test for regressions.

**Comment by LukeUsher** [comment]
The cause of the hang needs investigation, it may not be directly related to this PR, but another broken behavior that is exposed by this PR.

**Comment by gandalfthewhite19890404** [comment]
Interesting - trace build does not hang, game throws two log_cases and assertion - but its not related to this PR.
<details><summary> LOG_CASE </summary>
```
Please report that Prince of Persia: The Sands of Time shows the following message:
LOG_TEST_CASE: Unhandled PushBuffer Operation : NV2A_TX_OFFSET((0)*0x40) (0x1B00)
In HLE_pgraph_handle_method (c:\projects\cxbx-reloaded\src\cxbxkrnl\emud3d8\pushbuffer.cpp line 474)
```

```
Please report that Prince of Persia: The Sands of Time shows the following message:
LOG_TEST_CASE: Pushbuffer COMMAND_TYPE unknown
In EmuExecutePushBufferRaw (c:\projects\cxbx-reloaded\src\cxbxkrnl\emud3d8\pushbuffer.cpp line 648)
```
</details>
<details> <summary>Assertion </summary>
Assertion failed!
Program: D:\xb\pop_issue\1345trace\Cxbx.exe
File: c:\projects\cxbx-reloaded\src\devic...\emunv2a...aph.cpp
Line: 1626
Expression: vertex_attribute->count == 4
</details>

**Comment by RadWolfie** [comment]
@gandalfthewhite19890404 Please use #1355 pr build or later as it contain correct fix for this broken pull request. Then use #1355's build for further reports.

**Pull request merged**
