### PR TITLE
Fix IDirect3DDevice8_SetSoftDisplayFilter_1_0_5344

### PR DESCRIPTION
**Pull request by jarupxx**

### CODE REVIEW

**Comment by jarupxx** [comment]
True. It will be detected correctly. same as dxbx.

**Comment by PatrickvL** [comment]
Great, thanks. Which 5344 software title did you test with?

**Comment by jarupxx** [comment]
Likewise. It is Soldier of Fortune ii.

**Comment by PatrickvL** [comment]
Thanks, let's merge this.

**Pull request merged**
