### PR TITLE
Enable the use of PVS-Studio (Static Code Analysis Tool) 

### PR DESCRIPTION
**Pull request by LukeUsher**
These comments activate the free for Open Source license for PVS Studio
See http://www.viva64.com/en/b/0457/ for more details.

An initial run of PVS-Studio found the following:
460 high severity issues
146 medium severity issues
157 low severity issues

### CODE REVIEW

**Comment by BiatuAutMiahn** [comment]
Nice!

**Comment by PatrickvL** [comment]
Perhaps imports shouldn't be instrumented.

**Comment by PatrickvL** [comment]
A link to the current analysis results would be nice

**Comment by x1nixmzeng** [comment]
Compiling with LLVM does a great deal better than VS. Most of the warnings are to do with the `printf` format specifiers.

**Pull request merged**
