### PR TITLE
Refactor D3D device creation

### PR DESCRIPTION
**Pull request by CookiePLMonster**
This PR lays the foundation for migration to Direct3D9Ex by cleaning up and improving the correctness of D3D device creation:
* "Synchronization" via `volatile bool` variables has been completely removed - either by making it useless or by replacing with an event.
* `EmuCreateDeviceProxy` has been removed - now the entire process of device creation is done inline, with the exception of a call to `CreateDevice` - as it must be done on a window message thread (see the link below), it is now sent to an appropriate thread (in a blocking manner) via a newly added `RunOnWndMsgThread` function.

On threading considerations when creating, releasing or resetting D3D devices:
https://docs.microsoft.com/en-us/windows/win32/direct3d9/multithreading-issues

No changes are expected, but since it makes D3D9 usage more correct anything can happen - performance improvements are nearly impossible, but it **may** fix e.g. some lockups on startup. **Keep this open for a few days to have it tested, I'm especially curious about results of testing it on AMD GPUs without DXVK.**

### CODE REVIEW

**Review by PatrickvL — COMMENTED** [review]
Why remove the default assignment to only these global variables, when there's many more globals that could be treated similarly?

Either keep the initial assignments (which would communicate better what happens), or remove them for all global variables (although then this PR would contain unrelated code changes)?

**Comment by medievil1** [comment]
halo v1.09 and v1.01 black screen, just audio fro videos and wrong audio in menu
popup about timestamp (though I think that has been present for a while)
image

**Comment by CookiePLMonster** [comment]
> Why remove the default assignment to only these global variables, when there's many more globals that could be treated similarly?
> 
> Either keep the initial assignments (which would communicate better what happens), or remove them for all global variables (although then this PR would contain unrelated code changes)?

I'd say it's personal preference, for two reasons:
1. In this context, I'd rather communicate that there is "no default value" for those arrays (we know that on the binary level it's not true, but that's not my point), as we fill it with valid data on device creation.
2. `array[x] = { false };` creates a false impression that this `false` applies to each element of the array, it doesn't! Of course, in the case of `0`/`false` it doesn't matter, but it was `true` then it would.

I personally think most of those static variables should have their default assignments removed if not needed, but in this PR I only touched the init code for these particular format arrays.

**Review by PatrickvL — APPROVED** [review]

**Review by LukeUsher — APPROVED** [review]
Works fine for me, however I didn't notice any changes, AMD is still slow without dxvk

**Pull request merged**
