### PR TITLE
Misc build warning fixes

### PR DESCRIPTION
**Pull request by x1nixmzeng**

### CODE REVIEW

**Comment by PatrickvL** [comment]
Nice work! There's a few complaints from AppVeyor on this pr, though. Could you take a look?

**Comment by x1nixmzeng** [comment]
I can't understand why the logger doesn't work. I assumed it just piped stdout/stderr but it looks like it creates a special config :confused:

**Comment by PatrickvL** [comment]
I've asked @LukeUsher to check this out

**Comment by x1nixmzeng** [comment]
After re-reviewing my changes I'm not sure what this PR solves :confused: 

I'm tempted to close this and resurface the alignment fix with my XBE loading work

**Comment by x1nixmzeng** [comment]
Yeah, I'll do that.

Only thing to add is I'm not sure where the x64 config came from

**Pull request closed without merging**
