### PR TITLE
Fix random crashes in Panzer Dragoon Orta

### PR DESCRIPTION
**Pull request by LukeUsher**
This has been confirmed to fix the crashing and thread synchronization issues in Panzer Dragoon Orta

With this, it's now possible to play the game to completion, with or without the All Cores speed hack.

### CODE REVIEW

**Comment by AzurikRiseOfPerathia** [comment]
At least one game less to deal with;)

**Comment by PatrickvL** [comment]
On discord, gandalfthewhite reported : PR 1507 broke TES3 Morrowind - if you try to load game it throws error
Received Exception Code 0xC0000005 @ EIP := 0x04187D0D

**Comment by RadWolfie** [comment]
Regression titles with deadlock issue after a FMV video.
* Red Faction 2 (intro)
* Simpsons: Road Rage (intro)
* Crimson Skies (first in-game video)
* Blood Wake (can't see intro videos except does perform deadlock after first one)
* Haunted Mansion (first in-game video)
* Constantine (logo video(?) )

Titles not affected:
* Battlestar Galactica
* Turok Evolution

**Comment by gandalfthewhite19890404** [comment]
Add to list:

- The Elder Scrolls 3: Morrowind (BS-001 v1.01)
- WWE Raw 2 (seems only LLE GPU is affected)

**Pull request merged**
