### PR TITLE
Formatting

### PR DESCRIPTION
**Pull request by jarupxx**
Also remove few duplicate OOVPATable entries into D3D8.1.0.5788.inl, D3D8.1.0.5849.inl, DSound.1.0.5788.inl.

### CODE REVIEW

**Comment by PatrickvL** [comment]
Please, take a look at this : https://github.com/PatrickvL/Cxbx-Reloaded/blob/6f8abb8f788ed1b7f64ee4b8bb5fe59d8f68f02d/src/CxbxKrnl/HLEDataBase/D3D8.inl

It's a new way of registering OOVPA's - all versions concentrated into one big list per library.

Searches using that don't work yet, but once they work, all individual databases per version can be removed.

This is much easier to maintain than the structure we have now.

**Comment by PatrickvL** [comment]
https://github.com/PatrickvL/Cxbx-Reloaded/commit/78bcd2bacd1d9c57d79b1f263a5f13c7f8e12b6a also mentions a problem I previously found in your previous big submission. This was found just by pure luck. Please tell how we can verify you haven't made any mistake, and didn't lose any information?

**Comment by jarupxx** [comment]
I’m sorry, but there is no way to verify this pull request. I will close it. It may become unnecessary in the future, also we should discuss which formatting to use [Space] or [Tab].

**Comment by jarupxx** [comment]
In 5788, I copied 5849 as a template this work. Initial 5788 https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/118/commits/35556a235bfa7f722eb83091650113bf7f07fd6c It has not been confirmed at the time. (Of course, I verify is finished before make a pull request.)
I know D3DTexture_LockRect version 5558 was available as a result of verify completed, so I modified to reference 5558.

**Pull request closed without merging**
