### PR TITLE
Dsound refactoring Part 2

### PR DESCRIPTION
**Pull request by jarupxx**

### CODE REVIEW

**Comment by PatrickvL** [comment]
Thanks for this! It's good to see the OOVPA registrations are getting more manageable, and sound related code is becoming more consistent too.

**Comment by jarupxx** [comment]
Your change works fine. Great job!

**Comment by PatrickvL** [comment]
Which change are you referring to?

**Comment by jarupxx** [comment]
I make a mistake the Reply. I mean reply to this https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/180#issuecomment-280888335, that is Sound work # 181 is works fine.

**Pull request merged**
