### PR TITLE
Fix THPS2X Regression after PDO fix

### PR DESCRIPTION
**Pull request by LukeUsher**
Please don't merge until this has been verified to not break Panzer Dragoon Orta

### CODE REVIEW

**Comment by literalmente-game** [comment]
I'll run the game again with this PR to be sure

**Comment by literalmente-game** [comment]
LGTM :heavy_check_mark:

**Comment by LukeUsher** [comment]
@literalmente-game @StrikerX3 just got a hang in this branch, so we'll hold off merging a little while longer

**Comment by PatrickvL** [comment]
Any notification function that accesses thread local storage is at risk of accessing the wrong thread's storage - so either notifications need to be done within the new thread's context, or in the creating thread context.

**Comment by LukeUsher** [comment]
@PatrickvL I checked with a disassembly of the real kernel: The thread notification routine is called by the function creating the thread, not within the new thread. Calling the notification routine in the new thread, is what had caused THPS2X to hang. Turns out, this is something we've had wrong since forever.

**Comment by StrikerX3** [comment]
I confirm that this does fix the hangs. Great job Luke!

**Pull request merged**
