### PR TITLE
Port to HLSL (High Level Shader Language) vertex shaders

### LINKED ISSUE #1751: Convert Xbox vertex shaders to HLSL
Xbox vertex shaders are currently converted by Cxbx-Reloaded to shader (model 2) assembly. This has a few downsides, like register limitations, complicated register (re)allocation, instruction limits, etc.

For this issue, implement a converter for binary Xbox vertex shaders towards HLSL.

HLSL on Direct3d 9 (our current render API) allows a higher shader model, less limitations, more flexibility and easier conversion code.

One of the possible approaches discussed between current developers suggests to declare predefined functions for every operation Xbox shader assembly is capable of. Then, include this set of functions in a converted shader, and generate HLSL calls to those functions for each Xbox operation present in the Xbox shader that's being converted.

Obviously, the resulting shaders must be compiled, preferably once using a caching mechanism (initially in memory, later on disc to survive across reboots). Using cached shaders reduces the stutter/lag that results from shader conversion and compilation.

### PR DESCRIPTION
**Pull request by PatrickvL**
This PR replaces the old vertex shader conversion code, that generated vertex shader assembly, with code that generates and compiles HLSL vertex shaders.

This significantly increases accuracy of the emulated vertex shader program behaviour, with improved rendering as a result.

For some users, this might result in slower emulation, depending the speed of shader compilation.
Once compiled, the HLSL vertex shaders seem to be somewhat better optimized, resulting in slightly better frame rates.

Although we've already received reports of improvements in quite a few titles, there's also a few known regressions : Scaler (hangs a few seconds after going in-game, only the hair of the main character is visible), Buffy - Chaos Bleeds (doesn't reach menus) and Predator - Concrete Jungle (doesn't reach menus).

Still, the benefits are big enough to at least issue this work as a pull request, in order to get some more testing done.

Reviews of the code, and reports of other regressions (when proven related to this PR) are welcome in the comments.

Note : As the commit log shows, NZJenkins initiated this work, later on it became a joined-effort. It's great to be able to work together on things like this!

Fixes #1751

### CODE REVIEW

**Comment by ESPPIRAL** [comment]
The xbox Dashboard is missing graphics.

Cxbx-Reloaded 96952caf (Dec 17 2019) _ Emulating FFFE0000 v1 269657856 (Xbox Dashboard) 17_12_2019 18_01_00

**Comment by ESPPIRAL** [comment]
All this games now render to a black screen.

Cxbx-Reloaded 96952caf (Dec 17 2019) _ Emulating AY-004 v1 01 (Dreamfall) 17_12_2019 18_21_20
Cxbx-Reloaded 96952caf (Dec 17 2019) _ Emulating MS-019 v1 05 (BLiNX_ the time sweeper) 17_12_2019 18_16_45
Cxbx-Reloaded 96952caf (Dec 17 2019) _ Emulating TT-001 v1 01 (4x4 Evolution 2) 17_12_2019 18_08_41

**Comment by gandalfthewhite19890404** [comment]
Raw 2 now hangs before the match.
Black renders nothing, ironically, black screen. And it hangs just before the mission.

**Comment by LukeUsher** [comment]
@ESPPIRAL's black screen issues (including dashboard) seem to be GPU vendor specific: I am unable to reproduce those on my machine.

**Comment by gandalfthewhite19890404** [comment]
MGS 2 now crashing Exception Code 0xC00000FD @ EIP := 0x54628C67.

**Comment by medievil1** [comment]
crash nitro cart did have this in the log 
```DEBUG: VTXSH   I:\cxbx\games\Crash Nitro Kart\Shader@0x1235E080(310,3-6): warning X3550: array reference cannot be used as an l-value; not natively addressable, forcing loop to unroll```

**Comment by LukeUsher** [comment]
The benefits far outweigh any regressions, good to merge.

**Pull request merged**
