### PR TITLE
Stretch movies

### PR DESCRIPTION
**Pull request by PatrickvL**
Ported back of Dxbx. Includes libyuv PR, so merge that first.

### CODE REVIEW

**Comment by bhodg22** [comment]
The video previews in namco museum seem to be broken 
namco

**Comment by PatrickvL** [comment]
Did they render better before?

**Comment by bhodg22** [comment]
Yes, they were fine before but just had flickering

**Comment by PatrickvL** [comment]
Thanks for checking this. Let's not intrduce regressions and pospone merging this, until it's fixed.

**Comment by PatrickvL** [comment]
@bhodg22 PS: Could you please test https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/367 too? (Then we know if the above problem is introduced by this stretching, or with the switch to libyuv.)

**Comment by bhodg22** [comment]
Can confirm the video is broken on #367

**Comment by PatrickvL** [comment]
@bhodg22 Could you please take a look at https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/367#issuecomment-293905774 ?

**Comment by ObiKKa** [comment]
Tested with the day-old build (From PR 370) which may include the (cancelled?) PR 366 adding video support. Video previews of all games are fine just like on older builds in the first three months of this year. Yes, of course, the front end above it including both title logos, a white screen to the right side and control text options does flicker like usual.

2017-04-16_libyuv-test _01_galaga-preview

**Comment by PatrickvL** [comment]
Okay, thanks, the video pitch shows correct again. I suspect the placing is still not right - the white rectangle suggests the video should have been playing over there.

**Comment by ObiKKa** [comment]
Yes, you are correct. I found this Xbox version playback which shows the correct placement.
https://www.youtube.com/watch?v=c0QOjnYYCQM

**Comment by PatrickvL** [comment]
Thanks for confirming my suspicion with a YouTube link, much appreciated!

**Comment by ObiKKa** [comment]
Uh oh. Looks like bhodg22 was right. A few (?) things in among PR #367 pulled just now have been causing corrupted video previews and the videos are still not centred into the right slot area.
I am not able to include the un-pulled commits myself. I only grab builds from the appveyor platform.

2017-04-16 _01_corrupt-videos

**Comment by PatrickvL** [comment]
The previous PR merge was not complete. This PR merge should at fix the movie pitch, and should stretch movies to their intended size. Placing is another matter, which will be addressed later.

**Pull request merged**
