### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rexcaptain501**
This is a basic README.md cleanup rewrite.

### CODE REVIEW

**Comment by rexcaptain501** [comment]
@PatrickvL - if this is suitable for merging, should we request Kernel Debug files in Bug Reports?

**Comment by LukeUsher** [comment]
Definitely update this it request kernel debug files. Thanks!

**Comment by BenNottelling** [comment]
Looking good 👍 I support these changes 😊

**Comment by rexcaptain501** [comment]
I also added to report on what build being tested with.

**Comment by PatrickvL** [comment]
That's a good idea, but will take a lot of time to do

**Pull request merged**
