### PR TITLE
Fix nxdk built xbe crash when the signature is all zeros

### PR DESCRIPTION
**Pull request by ergo720**
See #1083

### CODE REVIEW

**Comment by x1nixmzeng** [comment]
I have some XBEs from SmartXX - `reboot.xbe` is one which throws errors with the "thread local storage" header, but Cxbx doesn't handle the error properly.

Also I've just spotted `delete[] m_SignatureHeader;` should be `delete m_SignatureHeader;`

**Comment by ergo720** [comment]
m_SignatureHeader  is ```m_SignatureHeader = new uint08[m_Header.dwSizeofHeaders - (sizeof(m_Header.dwMagic) + sizeof(m_Header.pbDigitalSignature))];```, which is an array allocated on the heap and so, afaik, to delete it I should use ```delete[] m_SignatureHeader;``` and not a plain ```delete```

**Comment by ergo720** [comment]
Unable to reproduce, reboot.xbe is detected to have an invalid signature, it reboots to the dashboard as expected and then I close it, which doesn't cause any crash on my end, in both release and debug builds.

**Comment by x1nixmzeng** [comment]
Yes sorry your use of delete is correct - I was wrong about that!

The error I get from my test XBE occurs before checking the signature. Initializing in `Xbe::ConstructorInit` will fix it.

I've attached my test file here: [reboot.zip](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1935109/reboot.zip)

**Comment by ergo720** [comment]
My findings: your attached xbe indeed crashes, but only on debug builds, because m_SignatureHeader is left uninitialized: the reading of the xbe fails because it hasn't a TLS section. Looking at it with xbe explorer, I see it also lack the library version section in addition to the TLS section. The reboot.xbe that I have works correctly instead, xbe explorer confirms it has the missing sections (library and TLS). My guess is that my version was built with an XDK, whereas the one you uploaded was built with openxdk

Release
capture
Debug
capture1
Your reboot.xbe
capture2
My reboot.xbe
capture3

**Comment by x1nixmzeng** [comment]
@ergo720 thanks for investigating and for adding the fix. From the screenshots, your file looks like gamepad sample renamed

**Comment by PatrickvL** [comment]
Thank you!

**Pull request merged**
