### PR TITLE
This is not to be merged. this is only for testing purpose to test us…

### PR DESCRIPTION
**Pull request by jackchentwkh**
…ing exception handler to handle the patched rdtsc instructions. for me, the release build can reach 60 fps with MechAssault. although sometimes it still crashes, but the successful rate to get in game is much higher. need more tests to validate this idea.

### CODE REVIEW

**Comment by LukeUsher** [comment]
This is actually not a bad idea... Mind if I replace my recent rdtsc hack with this approach and clean it up a little?

**Comment by PatrickvL** [comment]
This is what was proposed before already Luke ;)

**Comment by jackchentwkh** [comment]
Luke, sure, why not. But after testing ExaSekleton, it's really a very special case that uses 313 rdtsc instructions. I might fix it a little bit. Or you can go ahead use it first, and I shall add my fix later.
the first thing is that the array to store the rdtsc address shall be enlarged to around 400. 
next, the pattern shall add more patterns such as:
0f 31 29
0f 31 f3
0f 31 E9
0f 31 2b
0f 31 50
0f 31 0f
0f 31 8d 
0f 31 d9
0f 31 57
0f 31 b9
0f 31 85
0f 31 83
0f 31 33
0f 31 f7
and most strange one is 
0f 31 0f 31, which repeat the rdtsc instruction twice, I don't know why it's doing this. 
this shall be treated in special care.

**Comment by LukeUsher** [comment]
Replaced by #1066 
Thanks!

**Pull request closed without merging**
