### PR TITLE
Pixel shader hlsl 

### PR DESCRIPTION
**Pull request by LukeUsher**
This PR is based from the new home of (and replacement for) the work done in #2128

original PR text by PatrickvL:
>
>Tadaa! This introduces completely rewritten pixel shader emulation, through HLSL.
>
>Marked as draft, because it's not been thoroughly tested yet, and it's very likely there's still a few issues here-and-there to iron >out (like better handling of sampler state, and most of the texture addressing modes are untested).
>
>Still, it's now at a point that produces relatively better results than before (when no other issues are hit), so : enjoy!>
>
>BTW : CookiePLMonster and NZJenkins have helped out fixing silly little overlooked things and other stuff, so a big thanks go out to them as well. Cheers!

### TODO
- [x] Fix particle effect regression with square/discoloured particles
- [ ] Verify all texture-addressing modes (see EOL comments in hlsl code)
- [x] Decide how fixed function pixel shaders are going to be treated.

#### Title regressions (marked once fixed)
- [x] Lego Star Wars II (Dark menus)
- [x] Madagascar (Black screen) (same effect broken in master)
- [x] Jet Set Radio Future (boost dash effect)
- [x] Blinx (video background broken)
- [x] Metal arms fog
- [ ] Baldur's Gate (UI transparency)
- [ ] others?

#### Titles that improved thanks to this
- Dinosaur Hunting (demo) : Alpha kill now works
- Turok Evolution: Correct lighting 
- Jet Set Radio Future: No longer blacked our scenery, graffiti works.
-  Star wars Obi Wan: Previously the textures on the characters were grey, or when the pixel shaders were disabled (Under hacks) the characters flashed all kinds of colors.

### Note
This branch also contains a HLSL fixed function pixel shader, written by NZKJenkins. This makes Cxbx-Reloaded no longer use host-fixed function by default.

(Although host fixed function is still available by pressing F2, which makes it still rely on D3D9 fixed function and for AMD GPU's causes shader-model related issues.)

(Our mid to long term goal is to fix all remaining issues, so that we can drop host fixed function and start porting to Direct3D 11)

### CODE REVIEW

**Comment by legend800** [comment]
Similar to the last PR, Outrun 2 can't reach reach gameplay before crash. In the closed PR, it couldn't load menus. Now it gets all the way to the point where gameplay is loaded before crashing. Fine on latest master.

2021-02-12 10_29_04-Cxbx-Reloaded a93ffd7 (Feb 12 2021) _ Emulating SE-054 v1 02 (Outrun 2)

**Comment by ancient-animal** [comment]
Gunvalkyrie has improved in this build, but this error appeared while a level was loading:

GunValkyrie - error in experimental build - 1 - while loading a level

After that problem happened, I closed the XBE file, then I opened it again, then I started the emulation process again.

This time, an error appeared BEFORE I could select a level:

GunValkyrie - error in experimental build - 2 - before I could select a level

**Comment by fantesykikachu** [comment]
Since this is returning to shader model 3.0, without restoring the workaround, is this likely to break AMD GPUs again.

**Comment by gandalfthewhite19890404** [comment]
Raw 2 crashes after FMVs, during Now loading, here is kernel log.
[KrnlDebug_2136_raw2crash.zip](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/5977218/KrnlDebug_2136_raw2crash.zip)

**Comment by medievil1** [comment]
Azurik MS-007 V1.01 missing character model 
image

**Comment by medievil1** [comment]
Crimson skies MS-033 V1.01 pop up error just as plane is suppose to come into view 
image

**Comment by medievil1** [comment]
Buffy the vampire slayer EA-018 V1.01 
Black screen during menu (previous it lacked text but had background and text highlight bar as well as buffy character image)

**Comment by medievil1** [comment]
Red Dead Revolver TT-026 V1.01
popup error after pressing start 
image

**Comment by medievil1** [comment]
JSRF SE-010 V1.01
Popup error @ 3d start 
image

**Comment by medievil1** [comment]
Pirates The legend of black kat EA-021 V1.03
been black screen for a while but would go in game (you could hear everything) 
Crashes with popup
image

**Comment by medievil1** [comment]
ST:Shattered universe TM-016 v1.65537
Popup error 
image

**Comment by medievil1** [comment]
KOTOR LA-003 v1.95126529 
popup error 
image

**Comment by legend800** [comment]
Not sure if we need to continue testing games and reporting the same error over and over. Let's wait for the fix and retest or at least just add all the affected games to a single post.

**Comment by medievil1** [comment]
KOTOR II LA-020 V1.08
Popup error 
image

**Comment by medievil1** [comment]
> 
> 
> Not sure if we need to continue testing games and reporting the same error over and over. Let's wait for the fix and retest or at least just add all the affected games to a single post.

was just giving them a wide pool to pull from to test against...

**Comment by legend800** [comment]
> 
> 
> > Not sure if we need to continue testing games and reporting the same error over and over. Let's wait for the fix and retest or at least just add all the affected games to a single post.
> 
> was just giving them a wide pool to pull from to test against...

They don't need tens of games in individual posts though. Just do it in one post so everyone doesn't get numerous notifications. It's clearly broken so I would take a break and get ready to retest once we have a fix.

**Comment by medievil1** [comment]
quick update to my report up above... definitely PS related on the error, if you disable Pixel shaders, the games listed boot for example :
image

**Comment by ancient-animal** [comment]
With this 0127e73 build, the sixth level of Gunvalkyrie (called "Naglfar's Pit 1") looks like this:

GunValkyrie - visuals in level 6 (Naglfar's Pit) with experimental build 0127e73 (Pull Request 2136)

In the stable build from the "master" branch (bf6d8b8), that level looks like this:

GunValkyrie - visuals in level 6 (Naglfar's Pit) with stable build bf6d8b8 from 2021-02-11

In that same stable build, the visuals in level 6 look like this while using the "GV Napalm" attack:

GunValkyrie - visuals in level 6 (Naglfar's Pit) with stable build bf6d8b8 from 2021-02-11 - 2 - while using GV Napalm attack

In that same stable build, the visuals in level 6 look like this while using the speed-boost feature:

GunValkyrie - visuals in level 6 (Naglfar's Pit) with stable build bf6d8b8 from 2021-02-11 - 3 - while using speed boost

You can see that using the "GV Napalm" attack or using the speed-boost ability adds some clarity in the stable bf6d8b8 build, but the build from this Pull Request (0127e73) won't gain clarity while using those features. Using "GV Napalm" or speed-boosting will still leave the screen as a pure dark blue.

**Comment by ESPPIRAL** [comment]
Dinosaur Hunting (demo) Tested on intel GPU
Looks like alpha kill is working.

Master

Cxbx-Reloaded bf6d8b8 (Feb 11 2021) _ Emulating XK-030 v1 01 (DinosaurHunting) 15_02_2021 18_45_20

PR
Cxbx-Reloaded 0127e73 (Feb 15 2021) _ Emulating XK-030 v1 01 (DinosaurHunting) 15_02_2021 18_43_49

**Comment by ESPPIRAL** [comment]
Turok Evolution (intel GPU)
Lighting is working 

Master
Cxbx-Reloaded bf6d8b8 (Feb 11 2021) _ Emulating AC-004 v1 02 (Turok Evolution) 15_02_2021 18_53_12

PR

Cxbx-Reloaded 0127e73 (Feb 15 2021) _ Emulating AC-004 v1 02 (Turok Evolution) 15_02_2021 18_53_13

**Comment by ESPPIRAL** [comment]
True Crime SOLA

Fixesd road.
Master

Cxbx-Reloaded bf6d8b8 (Feb 11 2021) _ Emulating AV-014 v1 08 (True Crime_ Streets of LA) 15_02_2021 18_59_18

PR

**Comment by ESPPIRAL** [comment]
Richard Burns Rally

Master
Cxbx-Reloaded bf6d8b8 (Feb 11 2021) _ Emulating SC-005 v1 257 (Richard Burns Rally) 15_02_2021 19_24_06

PR
Cxbx-Reloaded 0127e73 (Feb 15 2021) _ Emulating SC-005 v1 257 (Richard Burns Rally) 15_02_2021 19_27_20


Master
Cxbx-Reloaded bf6d8b8 (Feb 11 2021) _ Emulating SC-005 v1 257 (Richard Burns Rally) 15_02_2021 19_23_46

Pr
Cxbx-Reloaded 0127e73 (Feb 15 2021) _ Emulating SC-005 v1 257 (Richard Burns Rally) 15_02_2021 19_22_47

**Comment by ESPPIRAL** [comment]
Tomb raider shows this instead of going ingame with black screen

Screenshot 15_02_2021 19_57_05

**Comment by ESPPIRAL** [comment]
Sneakers

Master
Cxbx-Reloaded bf6d8b8 (Feb 11 2021) _ Emulating MS-035 v1 02 (Sneakers) 15_02_2021 20_03_32

PR
Cxbx-Reloaded 0127e73 (Feb 15 2021) _ Emulating MS-035 v1 02 (Sneakers) 15_02_2021 20_01_44

Master 
Cxbx-Reloaded bf6d8b8 (Feb 11 2021) _ Emulating MS-035 v1 02 (Sneakers) 15_02_2021 20_04_36

PR
Cxbx-Reloaded 0127e73 (Feb 15 2021) _ Emulating MS-035 v1 02 (Sneakers) 15_02_2021 20_02_38

**Comment by ESPPIRAL** [comment]
Sega GT Online

Master
Cxbx-Reloaded bf6d8b8 (Feb 11 2021) _ Emulating SE-033 v1 05 (segaGTOnline) 15_02_2021 20_20_48

PR
Screenshot 15_02_2021 20_10_17

Master
Cxbx-Reloaded bf6d8b8 (Feb 11 2021) _ Emulating SE-033 v1 05 (segaGTOnline) 15_02_2021 20_21_47

PR
Cxbx-Reloaded bf6d8b8 (Feb 11 2021) _ Emulating SE-033 v1 05 (segaGTOnline) 15_02_2021 20_20_48

**Comment by ESPPIRAL** [comment]
Outrun 2

Master
Cxbx-Reloaded bf6d8b8 (Feb 11 2021) _ Emulating SE-054 v1 01 (OutRun2) 15_02_2021 20_32_03

PR
Cxbx-Reloaded 0127e73 (Feb 15 2021) _ Emulating SE-054 v1 01 (OutRun2) 15_02_2021 20_32_05

Master 
Cxbx-Reloaded bf6d8b8 (Feb 11 2021) _ Emulating SE-054 v1 01 (OutRun2) 15_02_2021 20_32_55

PR
Cxbx-Reloaded 0127e73 (Feb 15 2021) _ Emulating SE-054 v1 01 (OutRun2) 15_02_2021 20_32_57

**Comment by ESPPIRAL** [comment]
Hitman Contracts

Master
Cxbx-Reloaded bf6d8b8 (Feb 11 2021) _ Emulating ES-018 v1 04 (Hitman Contracts) 15_02_2021 21_07_03

PR
Cxbx-Reloaded 0127e73 (Feb 15 2021) 15_02_2021 21_05_13

**Comment by legend800** [comment]
Outrun 2 boots now and renders some more graphics, but no idea how ESPPIRAL is getting such a clear image with no smearing. This is what I get:

2021-02-15 14_02_14-Cxbx-Reloaded 0127e73 (Feb 15 2021) _ Emulating SE-054 v1 02 (Outrun 2)

**Comment by legend800** [comment]
> 
> 
> > Outrun 2 boots now and renders some more graphics, but no idea how ESPPIRAL is getting such a clear image with no smearing.
> 
> AMD vs NVidia behaviour maybe? 🤷

Weird, I'm on a Nvidia 3070. Maybe the clearing problem is related to that? Anyway thanks for the info, let's get back on topic.

**Comment by ESPPIRAL** [comment]
Aeon Flux

Master
Cxbx-Reloaded bf6d8b8 (Feb 11 2021) _ Emulating MJ-020 v1 01 (Aeon Flux) 16_02_2021 17_14_18

PR
Cxbx-Reloaded 0127e73 (Feb 15 2021) _ Emulating MJ-009 v1 01 (Advent Rising) 16_02_2021 17_12_27

**Comment by ESPPIRAL** [comment]
> Outrun 2 boots now and renders some more graphics, but no idea how ESPPIRAL is getting such a clear image with no smearing. This is what I get:
> 
> 2021-02-15 14_02_14-Cxbx-Reloaded 0127e73 (Feb 15 2021) _ Emulating SE-054 v1 02 (Outrun 2)

I am testing on Intel GPU, that may be the difference

**Comment by medievil1** [comment]
after latest push 2017 loader debug build has this 
image

regular release build is fine

**Comment by MarioSonic2987** [comment]
Fixes missing textures on level 7 in Crash Bandicoot: The Wrath of Cortex.

**Before**:
image

**After**:
image

**Comment by medievil1** [comment]
dunno when it happened, but red dead revolver is broken... white screen... F2 fixes it....

**Comment by medievil1** [comment]
blinx video background is broken in current ps_hlsl (not checked to see if the hlsl fixes pr fixes it yet)
image

**Comment by medievil1** [comment]
also PGR, broken as it is, has differences with F2, 
color of the speedometer needle and car shadow for example
image
with F2
image

**Comment by Foxlum** [comment]
Hey, AMD (GCN 5th Gen "Vega" iGPU) user here, JSRF runs completely fine, no blackout of scenery (unlike master). slowness only because of screen recording via screentogif.

https://user-images.githubusercontent.com/25959143/117093904-e4452a80-ad27-11eb-9bc1-681221679b3a.mp4

(master)

https://user-images.githubusercontent.com/25959143/117094245-e52a8c00-ad28-11eb-98d1-98fcc0e47e91.mp4

**Comment by BSBussell** [comment]
> 
> 
> @LukeUsher @PatrickvL Hey, AMD (GCN 5th Gen "Vega" iGPU) user here, JSRF runs completely fine, no blackout of scenery (unlike master). slowness only because of screen recording via screentogif.

In a build I compiled a while ago it seemed to be working ok, but the boost dash effect is broken again this time nearly obscuring the entire screen... I don't know if you all are already aware of the issue but I thought leaving a comment about it couldn't hurt.

**Comment by danifunker** [comment]
Star wars Obi Wan seems to be working much better in this branch.

This Branch:
image

Master Branch:
Previously the textures on the characters were grey, disabling the pixel shaders (Under hacks) made the characters flash all kinds of colors. 

Here is running the same game without the hack enabled.
image

This is on a GTX1650

**Comment by medievil1** [comment]
Metal arms is broken 
the PR 
image

And on Master
image
@NZJenkins

**Comment by literalmente-game** [comment]
From some quick tests, results are very positive:

- 187 Ride Or Die: minor visual improvements
- 25 To Life: no changes
- Animaniacs - The Great Edgar Hunt: no changes
- Aquaman - Battle for Atlantis: no changes
- Backyard Wrestling: no changes
- Backyard Wrestling 2: no changes
- Battlestar Galactica: no changes
- Bloody Roar Extreme: no changes
- Breakdown: no changes
- Crash Bandicoot: The Wrath of Cortex: major visual improvements
- Crime Life - Gang Wars: no changes
- Dragonball Z Sagas: no changes
- Dragon's Lair 3D - Return to the Lair: no changes
- GTA Vice City: minor visual improvement
- Gun: major visual improvement
- Just Cause: major visual improvements
- Land of the Dead - Road to Fiddler's Green: no changes
- Metal Slug 3: no changes
- Metal Slug 4: no changes
- Metal Slug 5: no changes
- Minority Report: no changes
- ObsCure: no changes
- Red Dead Revolver: major visual improvements
- Richard Burns Rally: major visual improvements
- Serious Sam: no changes
- Serious Sam II: minor visual improvements
- Silent Scope Complete: no changes
- Sneakers: major visual improvements
- The Legend of Spyro A New Beginning: no changes
- Top Spin: no changes
- Van Helsing: no changes

**Comment by LukeUsher** [comment]
Based on strelok’s testing, I’m happy to move this away from draft for final review/merge

**Comment by lorn10** [comment]
Hi all, I have now also tested the "pixel shader" build 096a8f3 and can confirm a **significant graphics improvement** in **Baldur's Gate Dark Alliance**:
Screenshot_20210529_105604
Screenshot_20210529_105417


Versus regular master build 8087b15:
Screenshot_20210529_110339
Screenshot_20210529_110245
The only small regression (if it really is one) is the missing transparency at the black "status bar" where the green "A" and red "B" button is displayed. At the regular master build it is slightly transparent while it is a the "pixel shader" build fully black.

However, unfortunately the game-state is still not fully playable, it is just "almost playable" because of the following annoying crash message. That "unhandled exception" 0xC0000005 only occurs in the cellar level. This is reproducible (on every build), but sometimes it is for whatever reason possible to play quite a while until it appears. (Maybe this is just a small, small thing to fix...)

Screenshot_20210529_105936

**Review by LukeUsher — COMMENTED** [review]
This work has been in-progress for around 6 months now, it has reached a point where the benefits far outweigh any risk of merging.

**Review by CookiePLMonster — APPROVED** [review]

**Pull request merged**
