### PR TITLE
Remove scanning D3DX8 library HACK

### PR DESCRIPTION
**Pull request by jarupxx**
We get the appropriate error message run the LTCG titles.
message

### CODE REVIEW

**Comment by jarupxx** [comment]
Only one function, D3D_CreateDeviceX was linked. Actually, this function located into the D3D Section (NOT D3D8X!). Therefore, D3D8X function would be nothing.

**Comment by PatrickvL** [comment]
Okay, nice find!

**Comment by Sarkie** [comment]
did this get merged?

**Comment by PatrickvL** [comment]
Now it is ;) (A little late but I'm on holiday and Luke is busy with NV2A LLE)

**Comment by Sarkie** [comment]
@PatrickvL Sorry! Thought I'd seen it already committed via another PR. 

HAVE A HOLIDAY!

**Pull request merged**
