### PR TITLE
Formatting/cleanup

### PR DESCRIPTION
**Pull request by Margen67**
#1136

### CODE REVIEW

**Comment by ergo720** [comment]
@Margen67 Some lines that you removed aren't redundant, but just a coding style. For example, I intentionally leave two empty lines between public and private class members, between global macros and a global variables, and between the start of the code and the global variables. This, to distinguish them easier.

**Comment by Margen67** [comment]
> @Margen67 Some lines that you removed aren't redundant, but just a coding style. For example, I intentionally leave two empty lines between public and private class members, between global macros and a global variables, and between the start of the code and the global variables. This, to distinguish them easier.

Is there a limit to the newlines? 3-4 is excessive imo.

**Comment by ergo720** [comment]
I only use two empty lines at most. If there are more than that, it's either a mistake or someone else did it.

**Comment by RadWolfie** [comment]
Without clang-format workflow upstream, I will not review this pull request due to numerious of files are affected. Which I knew this will happen anyway, it is criticial to have clang-format styling implement upstream before do any heavy formatting / clean up. Main reason for this is different IDEs have their own flavor of how things are formatted along with some of the people have their own personal preference format as their custom default format.

**Comment by Margen67** [comment]
> Without clang-format workflow upstream, I will not review this pull request due to numerious of files are affected. Which I knew this will happen anyway. It is criticial to have clang-format styling implement upstream before do any heavy formatting / clean up. Main reason for this is different IDEs have their own flavor of how things are formatted along with some of the people have their own personal preference format as their custom default format.

@RadWolfie If you'd like I can give the regular expressions I used.

**Comment by ergo720** [comment]
@Margen67 The issue with this PR is that it doesn't really solve #1136. Without a means to enforce clang-formatting, as more PRs come in the future, the issue will be regenerated over time. In addition, these changes will introduce conflicts with the work of other developers. So, it's likely that we are going to reject this PR.

**Comment by Margen67** [comment]
> @Margen67 The issue with this PR is that it doesn't really solve #1136. Without a means to enforce clang-formatting, as more PRs come in the future, the issue will be regenerated over time. In addition, these changes will introduce conflicts with the work of other developers. So, it's likely that we are going to reject this PR.

It's already conflicting so I'll just close it.

**Pull request closed without merging**
