### PR TITLE
Typo fix for IDirectSoundBuffer_SetMinDistance patch

### PR DESCRIPTION
**Pull request by medievil1**

### CODE REVIEW

**Comment by medievil1** [comment]
disregard fd32cd6 it was just me updating/refreshing my fork and it snuck in here somehow...(should have done it locally , but knew it was huge-2 years + out of date)

**Comment by escape209** [comment]
Fixes the player car's engine sound in Burnout being inaudible in certain situations e.g. looking back.

**Comment by LanHikariDS** [comment]
Not sure if you were trying to fix Jedi Outcast's distance issue as well, but this doesn't do it...

**Comment by medievil1** [comment]
> 
> 
> Not sure if you were trying to fix Jedi Outcast's distance issue as well, but this doesn't do it...

nope just fixed a typo I found

**Review by RadWolfie — APPROVED** [review]
No risk, only a typo in header function's parameter name.

**Pull request merged**
