### PR TITLE
Add Title ID Hex

### PR DESCRIPTION
**Pull request by RadWolfie**
For complete review, see here: https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/1285/files.

Includes:
* Print to Xbe log.
* Print to KrnlDebug log.
* and already included from #1327 for HLE Cache file.
* Replace Alt to Hex for better details (Thanks @LukeUsher!)

### CODE REVIEW

**Comment by RadWolfie** [comment]
@gandalfthewhite19890404, are you fine with the result for HLE Cache file and Xbe info log?

**Comment by gandalfthewhite19890404** [comment]
Would you, please, add Alternate Title ID in KrnlDbg log too, looks like this:
[0x1B48] INIT: XBE TitleID : CM-080
[0x1B48] INIT: XBE Alternate Title ID: 434D0050
[0x1B48] INIT: XBE Version : 1.01

Thanks!

**Comment by LukeUsher** [comment]
I'd use a separate wording than this: TitleID is the disc serial number,this is the hex version. So maybe call it Title ID (Hex):

The reason I say this, is the Xbox already has a concept of "Alternate Title ID": This is a list in the Xbe of titles the game has permission to access: Eg: If a sequel wants to read the savedata for the original game, it'd have the original game title_id in the alternate title id list.

**Comment by RadWolfie** [comment]
Ready for merge once approve the changes.

**Pull request merged**
