### PR TITLE
Direct3D Unpatching

### PR DESCRIPTION
**Pull request by LukeUsher**
This PR unpatches a great deal of EmuD3D and generally increases stability.

Key Changes:

- The ->Lock field of resources is no longer trashed by our code, leading to more stability and less patches required to Xbox code
- Xbox Pixel Shader handles get returned to Xbox Code, rather than a host handle, this fixes a crash when titles expect to be able to read data from this handle.
- YUV overlays no longer required a host resource, they are copied to the framebuffer directly from the Xbox YUV data
- Many functions use trampolines to call the Xbox implementations, to keep internal state correct (Direct3DResource_Release, for example, calls the Xbox implementation, then frees the host resource if necessary)
- LoadVertexShaderProgram has been optimised and no longer causes the frame-rate to tank in titles that use it
- Unpatched Direct3D functions have been moved to a backup file, to avoid cluttering EmuD3D8.cpp with unused code.

Many titles are known to improve with these changes, there may still be a few regressions lurking, but so far it's a net positive, with titles such as Obscure, Sonic Heroes E3 Demo, Silent Hill 2, and many others now reaching in-game.

Based on the overall positive improvement, I'm happy with this now, and any remaining regressions can be identified and solved after the merge with master. 

There are still improvements that could be made, but I'm starting to get concerned about scope creep. The sooner this is merged, the better.

As an example of progress made in this branch, the following is a title that crashes very early in master, but has much better results here: 

https://www.youtube.com/watch?v=-gzO2edHJ9s

### CODE REVIEW

**Comment by LukeUsher** [comment]
Based on the massive improvements made to... well, most titles than I can count, I'm a little tempted to self merge and deal with any fallout later, if any... Unless there are any objections to this... almost every single title I tested improved in some way.

**Comment by CakeLancelot** [comment]
Just throwing this in: I've been following this branch and there haven't been any significant regressions on the games I've tested. I will do one final check, but as Luke said I've seen nothing but improvements.

**Comment by LukeUsher** [comment]
@CakeLancelot has reported that this may have some memory leaks, causing address space to be exhausted in some titles, this needs investigation. Hopefully nothing serious but I'll look into it.

**Comment by Margen67** [comment]
RollerCoaster Tycoon now shows this error:
error

**Comment by CakeLancelot** [comment]
> RollerCoaster Tycoon now shows this error:

Are you sure this only occurs on this branch? I've seen similar errors on other games, I solved it by simply starting the game again. (for reference, the game was Pulse Racer - I've been intending to make an issue but I haven't had time)

**Comment by Margen67** [comment]
Yes. I tested it with https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/0783a8d0787ba14915f4e3fcfad23b9d63fbdbce and I don't get the error.

**Comment by Voxel9** [comment]
From testing a handful of 4627 XDK samples, I experienced regressions in the following:
Fire, PlayField, BillBoard, BeginPush, Flares, MotionBlur, PointSprites

Fire, BillBoard, and MotionBlur just crash with an error now, but the other three just have slight rendering problems:
- In the Flares sample, the sun and flares no longer render.
- In the PointSprites sample, the particles are no longer transparent/have no alpha.
- Same issue as above persists for BeginPush; no more transparency in particles.

However, one improvement I've seen so far is FuzzyTeapot fully working again! Otherwise, all the rest work the same as they do on master.

**Comment by RadWolfie** [comment]
Recent fix for regression is confirmed fixed for most titles that had regressed in this PR. Good finding the cause @LukeUsher. 👍

@Voxel9 I suggest to re-test them again since @LukeUsher made the fix for regression few minutes ago.

@Margen67 Re-test RCT game again. It is much better result than before! However there are some did not trigger a visual refresh in background and UI for some reason when doing a tutorial or start a game. Other than that, it works quite well.

**Comment by Voxel9** [comment]
@RadWolfie I know he did; while I was half-way typing that up, I noticed and re-tested it all again

**Comment by RadWolfie** [comment]
Hmm... looks like @Voxel9 regression report still stand.

**Comment by LukeUsher** [comment]
I found the source of the XDK sample crash, but it's going to take some time to fix (as in, probably not today, but still within this week), so this PR is on hold for now. I have not yet found the cause of missing alpha channel, but I'll get to it.

Thanks for testing guys, I'll get this fixed asap.

**Comment by LukeUsher** [comment]
There may still be some rendering issues in the XDK samples, but the hard crashes should be resolved now.

**Comment by Voxel9** [comment]
They were indeed, thank you very much!

Moving on, unfortunately OutRun 2 menus have been hit pretty bad by this branch as well; now most of the graphics aren't rendering at all compared to the perfect rendering the master branch can do right now.
For reference: (Master on the left, Patch removal on the right)

capture10
capture11
capture12

**Comment by CakeLancelot** [comment]
I found another regression in this branch as well, here's a quote from what I said in the Discord channel:
>I'm encountering the same issue as Otnert where the screen isn't updating - only occurs in the experimental branch
For example in Zelda - Oni Link Begins (homebrew) in master the game is almost perfect but in the experimental branch sometimes the game's display will get stuck on one frame (continues to play fine otherwise, you can hear sounds responding to input, etc.)(edited)
I'll add it to the PR
 
Here is the message Otnert posted that I was referring to:

> Only real regressions I've noticed are the screen not updating every frame in some games/homebrew around when the texture hashing changes were introduced (ninja gaiden arcade, doomx menus when going ingame, deus ex invisible war opening cutscene, xboxadvance-v24, when playing any game)

Here is a GIF comparison of master vs this PR (in both GIFs I press start until the prompt is gone and walk in a circle):
Master 
PR

**Comment by jarupxx** [comment]
I tested Battlestar Galactica.
I do a bisect that 3daa3afe does not crash with FMV playback, 555e9008 is crashes.

3daa3afe 
```
[0x1FE8] WARN: EmuResource is not a valid pointer!
```
latest branch
```
[0x05E0] EmuD3D8.cpp: D3DResource_Register(
   pThis                : 0x11AF6270 -> X_D3DResource* {
   .Common               : 10C0002 :
    RefCount             : 2
    Type                 : (X_D3DCOMMON_TYPE)0x00040000 = X_D3DCOMMON_TYPE_TEXTURE
    IntRefCount          : 1
    ?D3DCreated          : 1
   .Data                 : 12D4000
   .Lock                 : 0}
   pBase                : 00000000
);
[0x05E0] EmuIDirect3DResource8_Register :-> Texture...
[0x05E0] EmuD3D8.cpp: D3DResource_Register : g_pD3DDevice8->CreateTexture D3D error (0x8876086C: D3DERR_INVALIDCALL: Invalid Call)
[0x05E0] WARN: CreateTexture Failed!

Error: 0x8876086C
Format: 844715353
Dimensions: 640x480
```

[KrnlDebug-3daa3afe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1697048/KrnlDebug-3daa3afe.txt)
[KrnlDebug-latest-branch.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1697049/KrnlDebug-latest-branch.txt)

**Comment by PatrickvL** [comment]
Format 844715353 is hex 0x32595559 is YUY2

**Comment by RadWolfie** [comment]
@CakeLancelot Yeah, identical to what's happening with RollerCoaster Tycoon title in-game only. Funny thing is, only the cursor is showing the activity.

**Comment by RadWolfie** [comment]
Hmm... doesn't resolve RollerCoaster Tycoon refresh visual issue. If I keep it in constant activity area, such as moving rides, people walking, etc. It works fine for visual result. However, if I move into area where there's no activity at all. It start not to update visual whenever I move around. Unless I perform a zoom in/out within active area, then it start showing the result fine again. 😕

**Comment by PatrickvL** [comment]
@RadWolfie Could you update https://github.com/Cxbx-Reloaded/game-compatibility/issues/472 with some new screenshots and emulation summary, please?

**Comment by LukeUsher** [comment]
Are we sure the Crimson Skies memory leak is new to this branch and not in master?  I've tracked down what happens (but not why yet) and it is in a region of code that shouldn't/hasn't changed (the memory manager returns 32MB to QuerySize() on a Vertex buffer, which doesn't seem right)

**Comment by LukeUsher** [comment]
Crimson Skies no longer leaks memory but crashes due to another reason (not sure if this is inline with master or not)

Outrun 2 Menus now render fine, but it runs out of memory when trying to get ingame, and will likely require unpatched SetStreamSource/GetStreamSource to get ingame: This is beyond the scope of this branch, but will be addressed in a new branch later.

**Comment by CakeLancelot** [comment]
> Are we sure the Crimson Skies memory leak is new to this branch and not in master?

The game doesn't boot in master at all which is why I mentioned it in relation to this branch, sorry for any confusion.

**Comment by LukeUsher** [comment]
Most of the nasty regressions have been ironed out, so I'm alright with merging this now.
Any additional issues, we will deal with separately.

**Pull request merged**
