### PR TITLE
Pixel shader hlsl

### PR DESCRIPTION
**Pull request by PatrickvL**
Tadaa! This introduces completely rewritten pixel shader emulation, through HLSL.

Marked as draft, because it's not been thoroughly tested yet, and it's very likely there's still a few issues here-and-there to iron out (like better handling of sampler state, and most of the texture addressing modes are untested).

Still, it's now at a point that produces relatively better results than before (when no other issues are hit), so : enjoy!

BTW : CookiePLMonster and NZJenkins have helped out fixing silly little overlooked things and other stuff, so a big thanks go out to them as well. Cheers!

### CODE REVIEW

**Comment by RinMaru** [comment]
Vexx has issues
Screenshot 2021-02-01 102936

**Comment by LukeUsher** [comment]
> Vexx has issues
> Screenshot 2021-02-01 102936
> Ty the Tasmanian Tiger now freezes as the First loading text shows up the Frame time is skyrocketing
> Crash TTR is also affected by high frametime causing a freeze

Can you please clarify if these behaviours are worse than the master builds or not? Saying "has issues" isn't that helpful unless we have a frame of reference.

**Comment by RinMaru** [comment]
> > Vexx has issues
> > Screenshot 2021-02-01 102936
> > Ty the Tasmanian Tiger now freezes as the First loading text shows up the Frame time is skyrocketing
> > Crash TTR is also affected by high frametime causing a freeze
> 
> Can you please clarify if these behaviours are worse than the master builds or not? Saying "has issues" isn't that helpful unless we have a frame of reference.

in Master it loads stuff fine

**Comment by PatrickvL** [comment]
> Vexx has issues (in Master it loads stuff fine only this PR is introducing the freezes and Texture issues)
> Ty the Tasmanian Tiger now freezes as the First loading text shows up the Frame time is skyrocketing
> Crash TTR is also affected by high frametime causing a freeze

I already see what's wrong : The pixel shader HLSL is not yet included in the `hlsl` subfolder. Once it is in, I'll delete all comments (including this one) Once you see that, please re-test.

**Comment by ancient-animal** [comment]
In the most recent stable build (commit f390c79), Gunvalkyrie has the full speed (around 59 frames-per-second).

In this build (commit 33fe488), Gunvalkyrie has the full speed during the logos, but the speed will slowly be reduced when the "Press Start" screen arrives. It will slowly deteriorate. It reached 1 frame-per-second.

In case previous problems are related to the changes in this "Pixel Shader HLSL" feature, I will tell you this about this game:
It has a visual effect that covers the whole screen during the fast-motion feature, but the game is still playable during the first five levels. But level six, called "Naglfar's Pit 1", is unplayable, because it has a nasty visual effect that covers the whole screen and completely disrupts the view. I recorded all of the details here, a long, long time ago:
https://github.com/Cxbx-Reloaded/game-compatibility/issues/180

**Comment by RinMaru** [comment]
> > Vexx has issues (in Master it loads stuff fine only this PR is introducing the freezes and Texture issues)
> > Ty the Tasmanian Tiger now freezes as the First loading text shows up the Frame time is skyrocketing
> > Crash TTR is also affected by high frametime causing a freeze
> 
> I already see what's wrong : The pixel shader HLSL is not yet included in the `hlsl` subfolder. Once it is in, I'll delete all comments (including this one) Once you see that, please re-test.

Same issue as last build but now Frametime skyrockets way earlier or freezes.
Vexx has same issues but now freezes as 3d graphics on the start select screen is rendered, becoming slower and slower.
Crash TTR now just fails to get anywhere

**Comment by ancient-animal** [comment]
In the previous draft build (commit 33fe488), the logos of Gunvalkyrie had the full speed, and the "Press Start" screen had the speed-reduction problem.

In this current draft build (commit 08ac762), the speed-reduction problem happened immediately, so the screen stayed black because of the 1-frame-per-second speed. When the logos finally appeared, they played at full speed. After the logos finished,  the screen stayed black and the frame-rate counter was locked at 59.98 FPS. I waited a long time and the "Press Start" screen appeared for less than one second and the screen became black again, and the frame-rate counter became locked at 44.49 FPS.

I waited longer and the first frame of the "Press Start" screen appeared (the words "Press Start" weren't rendered yet) and the frame-rate became locked to 22.75. (This time, the frame stayed during the freeze, instead of become black again.) Eventually, the frame-rate counter switched to 11.87 FPS. After that, I didn't want to wait, so I exited the emulator.

**Comment by ESPPIRAL** [comment]
Blinx is less glithy and shadows are now properly rendered
Master
Cxbx-Reloaded ad7328d (Jan 30 2021) _ Emulating MS-019 v1 03 (BLiNX_ the time sweeper) 01_02_2021 19_08_26

PR

**Comment by ESPPIRAL** [comment]
Master
Cxbx-Reloaded ad7328d (Jan 30 2021) _ Emulating MJ-013 v1 03 (BloodRayne 2) 01_02_2021 19_21_55

PR

Cxbx-Reloaded 08ac762 (Feb  1 2021) 01_02_2021 19_21_00

**Comment by ESPPIRAL** [comment]
Bruce Lee QOD

No more Blue characters.
Master

Cxbx-Reloaded ad7328d (Jan 30 2021) _ Emulating VU-022 v1 01 (Bruce Lee_ QOD) 01_02_2021 19_33_55 (1)

PR
Cxbx-Reloaded 08ac762 (Feb  1 2021) _ Emulating VU-022 v1 01 (Bruce Lee_ QOD) 01_02_2021 19_33_07

**Comment by ESPPIRAL** [comment]
Crimsom Skies
Master
Cxbx-Reloaded ad7328d (Jan 30 2021) _ Emulating MS-033 v1 01 (Crimson Skies) 01_02_2021 19_41_46

PR
Cxbx-Reloaded 08ac762 (Feb  1 2021) _ Emulating MS-033 v1 01 (Crimson Skies) 01_02_2021 19_40_47

**Comment by ESPPIRAL** [comment]
Ghost Recon 2

Les vertex explosions on Master but better texturing on PR

Master
Cxbx-Reloaded ad7328d (Jan 30 2021) _ Emulating US-005 v1 02 (Ghost Recon 2) 01_02_2021 20_06_28

PR
Cxbx-Reloaded 08ac762 (Feb  1 2021) _ Emulating US-005 v1 02 (Ghost Recon 2) 01_02_2021 20_09_50

**Comment by ESPPIRAL** [comment]
Just Cause

Master

Cxbx-Reloaded 08ac762 (Feb  1 2021) _ Emulating SC-251 v1 01 (Just Cause) 01_02_2021 20_32_57
PR
Cxbx-Reloaded ad7328d (Jan 30 2021) _ Emulating SC-251 v1 01 (Just Cause) 01_02_2021 20_28_51

**Comment by medievil1** [comment]
hmmm interesting, Crimson skies, for me, does NOT render the plane texture... hmmm or if it does it is dark (wonder if it could be related tot he crash TWOC brightness issue on nvidia) 
image

**Comment by ESPPIRAL** [comment]
Richard Burns Rally

Master

Cxbx-Reloaded ad7328d (Jan 30 2021) _ Emulating SC-005 v1 257 (Richard Burns Rally) 01_02_2021 21_51_11

PR
Cxbx-Reloaded 08ac762 (Feb  1 2021) _ Emulating SC-005 v1 257 (Richard Burns Rally) 01_02_2021 21_48_57

**Comment by ESPPIRAL** [comment]
Sneakers 

Master


Cxbx-Reloaded ad7328d (Jan 30 2021) _ Emulating MS-035 v1 02 (Sneakers) 01_02_2021 22_16_59

Cxbx-Reloaded ad7328d (Jan 30 2021) _ Emulating MS-035 v1 02 (Sneakers) 01_02_2021 22_16_58

PR
Cxbx-Reloaded 08ac762 (Feb  1 2021) 01_02_2021 22_15_16

**Comment by medievil1** [comment]
just leaving documentation (I known it is known issue) that Buffy won't even run unless you bypass (f2) because of the failed shader compile (I assume) 
```[0x2968] INFO : VTXSH   Please report that Buffy: The Vampire Slayer shows the following message:
LOG_TEST_CASE: Couldn't assemble recompiled shader
In EmuCompileShader (D:\a\Cxbx-Reloaded\Cxbx-Reloaded\src\core\hle\D3D8\Direct3D9\Shader.cpp line 102)```

**Comment by jackchentwkh** [comment]
Steel Battalion regressed. In master the intro is shown. But in this PR it's all black screen.

**Comment by gandalfthewhite19890404** [comment]
**WWE RAW 2** hangs after Press START screen
**Black** no more boots, just hangs after boot.

**Comment by legend800** [comment]
I was hoping this would be the PR that fixes Outrun 2's gfx but it unfortunately breaks the game instead. White screen when hitting the main menu. Unable to proceed.

2021-02-07 00_18_07-Cxbx-Reloaded 08ac762 (Feb  1 2021) _ Emulating SE-054 v1 02 (Outrun 2)

**Comment by medievil1** [comment]
dunno, can't really do any testing yet, until the hang/can't compile pixel shader issue is fixed.... 90% of my games won't run unless I hit F2 currently with this PR

**Comment by RinMaru** [comment]
> dunno, can't really do any testing yet, until the hang/can't compile pixel shader issue is fixed.... 90% of my games won't run unless I hit F2 currently with this PR

only fix will be dx11 i think is what Luke said and thats awhile away

**Comment by medievil1** [comment]
> 
> 
> > dunno, can't really do any testing yet, until the hang/can't compile pixel shader issue is fixed.... 90% of my games won't run unless I hit F2 currently with this PR
> 
> only fix will be dx11 i think is what Luke said and thats awhile away

not sure he meant THAT exact issue... this is just a vs/ps version format issue....

**Comment by LukeUsher** [comment]
replaced by/migrated to #2136

**Pull request closed without merging**
