### PR TITLE
merged ALIAS OOVPA with multiple patterns into one (part 2)

### PR DESCRIPTION
**Pull request by jarupxx**
Continuation of PR #333 .
I have completed this task #323  except for D3DDevice_SetVertexShaderConstant1Fast.

### CODE REVIEW

**Comment by PatrickvL** [comment]
Wow, that's a lot of work! Did you already do regressions tests? And with what titles?

**Comment by jarupxx** [comment]
Okay, I used the following titles for regressions tests. All titles passed.

Azurik - Rise of Perathia (3911)
Halo (3925)
Jet Set Radio Future (4134)
Smashing Drive (4242)
Crash Bandicoot - Wrath of Cortex (4361)
Buffy the Vampire Slayer (4432)
Crazy taxi 3 (4531)
Turok - Evolution (4627)
Quantum Redshift (4721)
Namco Museum (4831)
Shikigami no Shiro Evolution - Red (5028)
Otogi (5120)
All-Star Baseball 2004 (5233)
Starsky And Hutch (5344)
Star Wars - Knights of the Old Republic (5455)
Battlestar Galactica (5558)
XIII (5558)
Dance Dance Revolution Ultramix (5659)
All-Star Baseball 2005 (5788)
Puyo Pop Fever (5849)
Forza Motorsport (5849)

**Comment by LukeUsher** [comment]
Nice, that's fairly rigorous testing
I'm satisfied with that

**Comment by ObiKKa** [comment]
And with that, you've passed Echelon9 into 3rd place on the contributions list. Congratulations!

**Comment by jarupxx** [comment]
@ObiKKa Thank you for your congratulations! I'm happy. I think this project is going very fun!

**Pull request merged**
