### PR TITLE
Fix Default Audio Frequency

### PR DESCRIPTION
**Pull request by RadWolfie**
Some titles with audio speed up such as
- GTA 3 **(confirmed)**
- GTA Vice City **(confirmed)**
- MechAssault **(confirmed)**
- Dragon's Lair **(no change)**
- Half-Life 2 **(confirmed by @Margen67)**
- Hobbit **(confirmed by @medievil1)**

should be resolved by this pull request.

### CODE REVIEW

**Comment by Margen67** [comment]
Improves sound in Half-Life 2.

**Comment by gandalfthewhite19890404** [comment]
WWE RAW 2 still has issues with announcer voices, also crowd noise does not sounds as should.

**Comment by RadWolfie** [comment]
Force pushed's diff is https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/a375faba5184605c8ccdd61b23fbb0331e604703#diff-4859415bafa54277eb749c659b827a8fL1673-R1695

Minimized equation coding to set Xb_Frequency variable directly then set the value to host's.

**Comment by RadWolfie** [comment]
@gandalfthewhite19890404, WWE RAW 2 will still have audio issue anyway (not a regression). It will require further investigation. Some of the audio issues may be address in the next pull request.

**Comment by literalmente-game** [comment]
MechAssault "jet pack" sound is now correct. Dragon's Lair high pitched tutorial voices are still high pitched

**Comment by RadWolfie** [comment]
I had troubleshoot with a tester to figure out the reason Dragon's Lair title's tutorial voices are still high pitched. Since SetFrequency was called first before SetFormat (debug is to force default frequency in parameter) was called. I tried a theory with no confirmation from DirectSound's API doc on msdn didn't resolve the issue. At least it is not a regression.

Since there's no regression, ready for merge.

**Comment by medievil1** [comment]
wasn't on the list but it fixes the sped up voices of the hobbit

**Pull request merged**
