### PR TITLE
XGSetTextureHeader leave unpatched

### PR DESCRIPTION
**Pull request by jarupxx**
Fix regressions in Taz Wanted reported by @literalmente-game https://github.com/Cxbx-Reloaded/game-compatibility/issues/149#issuecomment-327531583

### CODE REVIEW

**Comment by PatrickvL** [comment]
Before we merge this in, could you put a `#if 0 // Patch disabled` ... `#endif`-pair around the entire `XGSetTextureHeader` function - both in the .cpp *and* in the .h file?

**Comment by jarupxx** [comment]
D3DDevice_CreateTexture calls XGSetTextureHeader function not ready disabled this function.

**Comment by PatrickvL** [comment]
Ah, then it's good like this. Thanks!

**Comment by RadWolfie** [comment]
@PatrickvL Your request is no longer necessary. All it needs is UNPATCHED in inside central OOVPA v2 database. Comment `FUNC_EXPORTS` out should not be done either. We need to allow ALL `FUNC_EXPORTS` usable in order for asking tester, ourselves to re-test for needing to restore the patch or for troubleshooting. Not re-compiling every time to find out which patch needs to restore or needs to be disable.

**Comment by RadWolfie** [comment]
See issue #792

**Pull request merged**
