### PR TITLE
This seems to fix the .bik hang

### PR DESCRIPTION
**Pull request by LukeUsher**

### CODE REVIEW

**Comment by LukeUsher** [comment]
This also fixes dirty disc errors in some titles

**Comment by x1nixmzeng** [comment]
I did double-take when I read "ToUnicornSize" :laughing:

**Comment by LukeUsher** [comment]
Lol, wow, that's what I get for committing at 1am ;) the codes fine though!

**Comment by ObiKKa** [comment]
Is that from an Electric Dream?

**Pull request merged**
