### PR TITLE
Add DSound OOVPAs

### PR DESCRIPTION
**Pull request by jarupxx**

### CODE REVIEW

**Comment by LukeUsher** [comment]
Could you document the sources of these OOVPA values please, or rather, explain how you know these to be correct?

**Comment by jarupxx** [comment]
I would refer you to this documents.
https://github.com/jarupxx/cxbx_log/blob/master/Document_pr140.zip

**Comment by PatrickvL** [comment]
Thanks for your hard work! I'll merge this PR once the current version is tested on http://infinitycommunicationsgateway.net/Pub/CxbxBugs

**Comment by PatrickvL** [comment]
I caused a few conflicts in this PR, but was able to resolve these. Still waiting for that test ;)

**Comment by BiatuAutMiahn** [comment]
lol, i left cxbx running while i did some school work, and the log went up to 20GB!

**Pull request merged**
