### PR TITLE
Fix an issue where the wrong depth buffer was selected

### PR DESCRIPTION
**Pull request by LukeUsher**
This fixes a (stupid) bug where the Default Depth Stencil was always set, even if there was another active depth buffer.

### CODE REVIEW

**Comment by RadWolfie** [comment]
After careful code review, looks good to me.

I had tested known titles (list below) for any regress and have not find any regression.
* Red Faction 2
* Crimson Skies
* Jet Set Radio Future (improved, expand "JSRF improvement" for screenshots)

Other tittles did not appear to regress.

<details><summary>JSRF improvement</summary>

Before:
JSRF-before

After:
JSRF-after
</details>

However, Jet Set Radio Future is still using same position for 2nd viewpoint when using internal upscale.

**Comment by RadWolfie** [comment]
I am leaving this pull request open if Luke wants to implement any further fix toward internal upscale or not.

**Comment by PatrickvL** [comment]
Also, when handling device reset, this global variable should be nilled

**Comment by LukeUsher** [comment]
> Also, when handling device reset, this global variable should be nilled

We don't HLE the D3D Reset function, DirectX takes care of it on the Xbox side.
Internally, it frees the framebuffers which will trigger D3DResource_Release, causing the variables to be cleared.

**Comment by LukeUsher** [comment]
@RadWolfie thanks for testing

**Pull request merged**
