### PR TITLE
Fix an issue with memory.bin in wine

### PR DESCRIPTION
**Pull request by ergo720**
I tested this with a tiled memory of 64 MiB and it worked, however, for some reason using 128 MiB always fails (cannot map tiled memory). Considering that for PatrickvL this seems to work in that case as well, I guess it's because I have a different version of wine?

### CODE REVIEW

**Comment by ergo720** [comment]
Yeah, I thought that temp file was strange indeed

**Comment by PatrickvL** [comment]
Oops, a small miscommunication : 64 MiB worked under Windows - I didn't test with Wine. Sorry about that.

**Comment by ergo720** [comment]
I did, it worked

**Comment by ergo720** [comment]
I suppose I can delete the entire temp folder, not just the file?

**Comment by LukeUsher** [comment]
Looks good, thanks!

**Pull request merged**
