### PR TITLE
Issue Template

### PR DESCRIPTION
**Pull request by BenNottelling**
I think this is something that's been needed for awhile and it's been made apparent by quite a few useless issues, this may help show what's needed
Here's how the issues look:

### Description

[Description of the issue]

---

### Game info
[XBE Dump, KrnlDebug, HLE Cache, Ect]

---

### Status
**Previous behavior:** [Before regression]

**Current behavior:** [On the latest build]

---

### Screenshots [Errors, Graphics, Glitches, ECT]

---

### Additional Information

Any additional information such as configuration or other comments

### CODE REVIEW

**Comment by BenNottelling** [comment]
See how it looks with an actual issue: https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/600

**Comment by PatrickvL** [comment]
There's more to it than that. Eventually we'll move all compatibility issues towards a separate project. We'll update the issue titles to only show TitleID, name (and if needed a version identifier). Compatibility status and other attributes will be shown via labels. Only duplicates will be closed. Forum-like discussions will be deleted.

**Comment by PatrickvL** [comment]
Also, we need someone to keep it up to date. As it stands now, doing that is costing me time I can't spend on development

**Comment by BenNottelling** [comment]
@PatrickvL I'd be willing to keep it updated

**Comment by PatrickvL** [comment]
Thanks for that. I'll discuss it with Luke

**Comment by PatrickvL** [comment]
We'll get back to you on this

**Comment by BenNottelling** [comment]
Sounds great :) I listen to directions pretty well too. Boss's favorite dishwasher because I actually do things right 😁

**Comment by CakeLancelot** [comment]
I would be willing to help out as well if needed!

**Comment by PatrickvL** [comment]
Thanks. I was already expecting you to ;)

**Comment by LukeUsher** [comment]
I'll merge this for now : It's better than what we currently have, in a couple of months time, I hope to have compatibility list website back up, it should be easier to manage then!

**Comment by ObiKKa** [comment]
IMO, those linings and headings are too much work. Most of the new users wouldn't realise how to use the formatting styles. I'd rather put in text, screenshots, files and differentials of the behaviours.

**Comment by BenNottelling** [comment]
@ObiKKa lucky control+A, then delete works perfectly

**Pull request merged**
