### PR TITLE
Added various D3D OOVPAs

### PR DESCRIPTION
**Pull request by jarupxx**
NBA Ballers Phenom, SX Superstar and NBA Live 2002 now reaches a first frame!
Crash Nitro Kart and XIII. It seems Hotfixes was integrated in the library. Recent patterns will fail to detect functions.
To check the software used for testing and OOVPA values, I would refer you to this [documents](https://github.com/jarupxx/cxbx_log/blob/master/Document_pr_fnc-3.txt).

### CODE REVIEW

**Comment by LukeUsher** [comment]
You're doing great work!

**Comment by PatrickvL** [comment]
Why did you delete this file : "doc/Sorted Reordered Dxbx Patterns (D3D only as TXT, CSV and JSON).7z" ?

**Comment by jarupxx** [comment]
I'm sorry, I'm obviously wrong! Thank You For Pointing Out My Mistakes.

**Comment by LukeUsher** [comment]
All good, I've restored that file

**Comment by jarupxx** [comment]
Thank you for restored that file.

**Pull request merged**
