### PR TITLE
Interpret larger blocks during exception handler to reduce the number of exceptions per-frame

### PR DESCRIPTION
**Pull request by LukeUsher**
This is mostly preparation for things to come in the (near) future but has a little impact in its current form.

Some titles may see a 1-2 FPS increase using LLE, some titles may show 5+ FPS increase with HLE, but overall, the difference is minimal.

### CODE REVIEW

**Comment by gandalfthewhite19890404** [comment]
Cause regression with LLE GPU enabled, tested and confirmed on WWE Raw 2.
At previous Previous 1437 it get to Unknown IV_IMAGE_BLIT Method and further to ingame.


Latest 1440 just hangs just before that - IoCreateObject Failed. Stopping emulation does not terminate process - you can see high CPU load after it.

**Comment by PatrickvL** [comment]
Previously, we skipped unrecognised opcodes, but not anymore - perhaps that's causing the observed hanging?

**Comment by LukeUsher** [comment]
thanks, I'll investigate WWE Raw 2

**Comment by gandalfthewhite19890404** [comment]
But 1440 improves (you can see rotating ball much faster) 2002 FIFA World Cup with LLE GPU enabled. 
Just keep it in mind.

**Comment by gandalfthewhite19890404** [comment]
Same thing with The Sims. In Pre-1440 its get to Unknown NV_IMAGE_BLIT Method.
PR1440 - just hanges just before that on DSOUND-related warning.
Btw - The Sims throws to log many unsupported instructions on PR1440 - 4343, 223, 117, 793, 188, 987.

**Comment by PatrickvL** [comment]
Our current CPU emulator just stops interpreting once it hits an unsupported instruction, and resumes execution from that point onward on the host CPU. So from there on emulation behaves like usual. Interpretation is slower than native execution, but since it avoids our access violation handler for MMIO instructions, interpretation actually lowers overhead and thus improves overall performance.

**Comment by PatrickvL** [comment]
Interpretation starts when an MMIO instruction is hit, and ends on call, jump, return and unsupported instructions, like the ones mentioned above.

**Comment by PatrickvL** [comment]
That being said, by adding support for more instructions, interpretation could run longer pieces of hardware-accessing functions

**Comment by PatrickvL** [comment]
As for the fee titles that hang: most likely that's due to an unsupported instruction accessing uncommitted memory; Since it's unsupported, the host CPU is resumed on that instruction, it'll access this uncommitted memory, such once again triggers our exception handler, which tries to emulate the instruction, but it turns out to be unsupported. With that, the above described steps repeats indefinitely...

**Comment by LukeUsher** [comment]
@PatrickvL actually, I would be more inclined to believe the hangs to be caused by incorrect flag calculation, I need to go through every instruction and verify the behavior. Incorrect flag calculation could lead to infinite loops when conditional branches are used.

**Comment by gandalfthewhite19890404** [comment]
Mafia also hangs on 1440.

**Comment by PatrickvL** [comment]
There's a good chance a fix on this will alleviate the hang in all cases.

**Comment by PatrickvL** [comment]
@gandalfthewhite19890404 would you like to test #1444 again? We've improved CPU interpretation a bit, which might help...

**Comment by gandalfthewhite19890404** [comment]
WWE RAW2 is not fixed yet. Should I test other titles?

**Pull request merged**
