### PR TITLE
Potential fix for issue #688

### PR DESCRIPTION
**Pull request by ergo720**
JSRF goes ingame without the hack with this.  I tested all my other games and didn't see any regressions/improvements, but I don't have lego star wars so someone else must check it.

### CODE REVIEW

**Comment by PatrickvL** [comment]
Could you either this a little so there's only a single point of exit? (Mostly by keeping the original RETURN, and making sure all code paths flow there.)

**Comment by PatrickvL** [comment]
Congratulations on removing the only title-specific hack we had left, by the way!

**Comment by ergo720** [comment]
Better now? (there are also the usual indentation problems because I used spaces whereas the other code used tabs)

**Comment by LukeUsher** [comment]
Note to all: Make sure this gets a thorough testing before merging, at a minimum, Lego Star Wars, Jet Set Radio Future, Turok Evolution and Battlestar Galactica need to be checked to ensure controller support still works.

**Comment by PatrickvL** [comment]
Thanks, much better ;)

I can't test for a while, so hopefully someone else can.

**Comment by ergo720** [comment]
I played the first level of jsrf so that works but I don't have the other three games. The input works also for Panzer Dragon Orta if that helps

**Comment by PatrickvL** [comment]
If I remember correctly, we had a few titles with input related issues, like Quantum Red Shift, maybe it's a good idea to test a few of those too (look up issues labelled with 'issue-input' in the compatibility project)

**Comment by LukeUsher** [comment]
It's specific games that have issues, as Patrick and I mentioned. The key one to test is Lego Star Wars: There's never been a situation where both input works in Lego Star Wars, and JSRF actually boots, without hacks.

**Comment by ergo720** [comment]
I don't have any of those, with the exception of Halo which crashes with the same error of before

**Comment by LukeUsher** [comment]
We can't merge until somebody can test those games and verify that it works

**Comment by ergo720** [comment]
Ok, if it doesn't work, I'll try to buy that game as well

**Comment by RadWolfie** [comment]
@ergo720 this is very similar to my XGetDeviceChanges-Fix branch. However your's is so much more accurate for the else portion. 🎉 👍 

Sad news, it did regress for JSRF crash and Lego Star Wars is no longer getting any controller input.

**Comment by ergo720** [comment]
Pity, then we have to close this

**Comment by RadWolfie** [comment]
IMO, we should just restore the hack to the top and keep this new change for accuracy reason.

**Comment by ergo720** [comment]
You mean, comment out the modification and restore the hack so we can keep it for future reference?

**Comment by ergo720** [comment]
Ok, as @RadWolfie requested my modification is commented out and the hack restored

**Pull request merged**
