### PR TITLE
Fixed the pattern XNetStartup, WSAStartup

### LINKED ISSUE #129: [Regression] WSAStartup is not detected
Version fa30aa09d61b4e921f3a08016da8888ff34b76d6
WSAStartup is registered in XOnline.1.0.4627.inl, but detection fails.

I tested it with Whacked 1.0.4831.
[xbe.txt](https://github.com/jarupxx/cxbx_log/blob/master/Whacked%20Xbe.txt)

### PR DESCRIPTION
**Pull request by jarupxx**
Fixed #129 Those patterns no longer use XREF.

### CODE REVIEW

**Comment by PatrickvL** [comment]
Thanks for working on this. I do wonder - could these OOVPA's be kept unmodified if the XRef itself (XnInit) was improved/fixed instead? That would be an even better solution...

**Comment by jarupxx** [comment]
Exactly. These OOVPAs are available without modification.
Surely it is safer not to change existing OOVPA's...

**Comment by PatrickvL** [comment]
What I mean is, what if these two OOVPA's are kept totally unchanged, including their xref to XnInit, but instead update the OOVPA for XnInit. To determine that, a search in the XDK patterns and/or a test xbe like Whacked can be examined with a tool like XbeExplorer for example.

**Comment by jarupxx** [comment]
I modified OOVPA of XnInit. This value can be shared with XDK 4627 and 4831.

**Comment by PatrickvL** [comment]
Cool! Thanks for digging further into it, this is certainly a better solution.

**Pull request merged**
