### PR TITLE
Replace atomic boolean m_bFrameTime with a mutex m_FrameTimeMutex

### PR DESCRIPTION
**Pull request by PatrickvL**

### CODE REVIEW

**Comment by LukeUsher** [comment]
Why this replacement? Was there an issue with the existing boolean, or is the mutex faster?

**Comment by PatrickvL** [comment]
Here a discussion about this: https://www.reddit.com/r/cpp_questions/comments/3lbxpc/using_a_global_atomic_variable_instead_of_a_mutex/

**Comment by PatrickvL** [comment]
I should change all occurrences of "while not try_lock Sleep" to just "lock"...

**Comment by PatrickvL** [comment]
Please postpone merging this until I've done the lock-replacement

**Comment by PatrickvL** [comment]
Okay, done. I've rebased this, and replaced all "while try_lock() Sleep" constructs with just a lock()

**Pull request merged**
