### PR TITLE
Refactored LLE X86 and NV2A

### PR DESCRIPTION
**Pull request by PatrickvL**
Completed operand decoding
Completed opcode ADD
Redirected 8 and 16 bit memory accesses to 32 bit
EmuX86 logging fixes and cleanup
Partiall support for misaligned memory accesses
NV2A macro cleanup
Clearer NV2A logging
Generic read/write on most NV2A components

### CODE REVIEW

**Comment by BenNottelling** [comment]
@PatrickvL There is a "/" on line 1061 of EmuNV2A.cpp that seems out of place, removing this allowed the project to compile.

**Comment by PatrickvL** [comment]
Yeah, I tried to correct that with commit https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/5683709760f6638db460deddea9fcd4368e762db but it somehow got reversed. I'm not near a computer so I can't fix this now

**Comment by PatrickvL** [comment]
@BenNottelling : I've used the online GitHub edit feature to fix this here https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/76112b6a0f866261a597d5c11604156ab9a3a587
Could you test this?

**Comment by BenNottelling** [comment]
@PatrickvL It compiled correctly and was able to emulate Turok, so it looks all good! Nicely done

**Pull request merged**
