### PR TITLE
Support for controller vibration

### PR DESCRIPTION
**Pull request by x1nixmzeng**
Requires "Use XInput" to be checked from the settings menu

I've also removed logic which updates `g_pXInputSetStateStatus`, but any info on why it needs to poll there is welcomed!

### CODE REVIEW

**Comment by PatrickvL** [comment]
Nice work! Please ask for some tests on Discord or gitter. IMHO merging depends on that feedback.

**Comment by RadWolfie** [comment]
Works with Turok Evolution title for each damage taken, hitting the ground with axe, and slight vibration for shooting an arrow.

**Comment by Voxel9** [comment]
Glad to see somebody got this done! :)

**Comment by RadWolfie** [comment]
@x1nixmzeng I agree. Since hHandle is optional variable given to xbox, some titles may rely on this to be complete (via SetEvent). Otherwise it will hang.

**Pull request merged**
