### PR TITLE
Fix for issue #730

### PR DESCRIPTION
**Pull request by ergo720**
Tested with Tenchu (multi-xbe) and Panzer ORTA (which for me reboots to the dashboard) and also other single-xbe games. No regressions observed and "Stop Emulation" now works as intended

### CODE REVIEW

**Comment by PatrickvL** [comment]
Thanks for taking this one up - it's an annoying issue indeed.

I wonder, why don't you just put `m_hwndChild` in EmuShader instead??? That could make this implementation quite a bit simpler....

**Comment by ergo720** [comment]
Simply because I planned to use WM_COPYDATA in my input and LED branches anyway. For this case, though, is probably more simple to do what you say, so I'll need some time to update this

**Comment by ergo720** [comment]
After more thorough testing I came up with a much more simple fix, just 3 lines of code. I'm sure Patrick will appreciate the new implementation. I tested it again with the games of above and it works

**Comment by RadWolfie** [comment]
Honestly, I had some doubt with this new change _might_ modify our "Recent Xbe files" list. When I tested it out myself, it did not modify the "Recent Xbe files" for multiple xbe loads.

@ergo720 You have my approval. Congrats! 🎉

@PatrickvL Please merge this whenever you are satisfy with this change.

**Comment by RadWolfie** [comment]
Side note: It did not resolve the window title's name change when certain title has reboot to dashboard. Yet it is a separate issue anyway.

**Pull request merged**
