### PR TITLE
X86 expand

### PR DESCRIPTION
**Pull request by PatrickvL**

### CODE REVIEW

**Comment by gandalfthewhite19890404** [comment]
I can test it only tomorrow, sorry about that.

**Comment by PatrickvL** [comment]
This PR seems to cause a hang of it's own, still investigating... (test-case : XDK Cartoon sample)

**Comment by RadWolfie** [comment]
Is there a reason for cases being relocated? Curiously for the reason behind this.

**Comment by PatrickvL** [comment]
Yes, I've learned through experience that it pays off to order code (often alphabetically) so that is clear where something new belong s, conflicts are avoided, etc

**Comment by gandalfthewhite19890404** [comment]
[KrnlDebug_Raw2_InstrDump.zip](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/2406154/KrnlDebug_Raw2_InstrDump.zip)
Added log, its big due large amount of instuctions.

**Comment by medievil1** [comment]
found a typo (unimportant but it is there).. 
Buffy hangs, black screen, last lines of the dbg have the typo:
INIT: Done patching rdtsc, total 5 rdtsc instructions patched
InitXboxControllerHostBridge: Host XInput port greater then total xinut controller connected. disconnect xbox port from host!
InitXboxControllerHostBridge: Host XInput port greater then total xinut controller connected. disconnect xbox port from host!
InitXboxControllerHostBridge: Host XInput port greater then total xinut controller connected. disconnect xbox port from host!
Currently running it with full debug options 
Seems it likes location 0000000 and the same instruction ADD:
[0x246C] WARN : X86     EmuX86_Mem_Write Failed (0x00000000, 0x00000000, 1)
[0x246C] INFO : X86     Processed instruction : ba8b9d ADD dword ptr [EAX+0],AL
[0x246C] WARN : X86     EmuX86_Mem_Read Failed (0x00000000, 1)
[0x246C] X86     Read(0x00000000, 1) = 0x00000000
[0x246C] X86     Write(0x00000000, 0x00000000, 1)
[0x246C] WARN : X86     EmuX86_Mem_Write Failed (0x00000000, 0x00000000, 1)
[0x246C] INFO : X86     Processed instruction : ba8b9f ADD dword ptr [EAX+0],AL
[0x246C] WARN : X86     EmuX86_Mem_Read Failed (0x00000000, 1)
[0x246C] X86     Read(0x00000000, 1) = 0x00000000
[0x246C] X86     Write(0x00000000, 0x00000000, 1)
[0x246C] WARN : X86     EmuX86_Mem_Write Failed (0x00000000, 0x00000000, 1)
[0x246C] INFO : X86     Processed instruction : ba8ba1 ADD dword ptr [EAX+0],AL

I am truncating the file since it is the same thing over and over
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/2406439/KrnlDebug.txt)

**Comment by gandalfthewhite19890404** [comment]
Almost all titles are hangs with these errors.

**Comment by medievil1** [comment]
ummm is this correct? 	
		        case I_JMP: {
			case I_JMP: // = 462 : 	Jump
			case I_JMP_FAR: { // = 467 : Jump
				if (EmuX86_Opcode_JMP(e, info)) {
					continue;
				}
				break;

it;s at location 1396 first case I_jmp was removed, second and Jmp_far added shouldn't the added I-Jmp have a { ...like this case I_JMP: { //=462 : Jump

**Comment by PatrickvL** [comment]
@medievil1 it was intentional to fall-through and handle far jump using the same code as jump. I can't explain why your added curly brackets fixed Buffy for you

**Comment by medievil1** [comment]
> 
> 
> @medievil1 it was intentional to fall-through and handle far jump using the same code as jump. I can't explain why your added curly brackets fixed Buffy for you

yea, thats why i said it was weird... I'd figured out why it was that way, but had already set up the build so built it anyway...wasn't expecting it to work....there was an issue with jmp though that luke fixed.. perhaps I bypassed the issue unintentionally enough for the game to continue...

**Comment by gandalfthewhite19890404** [comment]
DO NOT MERGE IT -NEED TO MORE TESTING!

**Comment by hotzenplotz3000** [comment]
@PatrickvL : Is a Log filter for only x86 enough for you or should I make a full Log?
I would try some games later today.

**Comment by PatrickvL** [comment]
We don't need logs at this moment, thank you

**Comment by PatrickvL** [comment]
The instruction logging I added probably causes quite some overhead, it can be avoided if we insert a check before calling the logging function, to verify x86 debug logging is turned on or not

**Comment by LukeUsher** [comment]
Merging since this fixes some significant issues.
Further work can be made into an additional PR

**Pull request merged**
