### PR TITLE
Implement D3D8LTCG specific functions

### PR DESCRIPTION
**Pull request by jarupxx**
It does not change standard functions, so it should not affect the behavior.
trampoline does not work, but we welcome to update!

trampoline issue
- D3DDevice_SetTexture_4
- D3DDevice_SetStreamSource_4
- D3DDevice_SetPixelShader_0

Broken 
- D3DDevice_GetViewportOffsetAndScale_0 Test-case RalliSport Challenge 2 title.

Untested
- D3DDevice_EndVisibilityTest_0
- D3DDevice_SelectVertexShader_4
- D3DDevice_DeleteVertexShader_0

### CODE REVIEW

**Comment by jarupxx** [comment]
Improve compatibility
Ninja Gaiden :P
ninja

**Comment by PatrickvL** [comment]
Please wait merging this until it's rebased onto master once the current D3D pull requests are merged. This, because this pull request intrudes multiple versions of EMUPATCH(Direct3D_CreateDevice*), which changed in the current D3D pull requests

**Comment by jarupxx** [comment]
Alright. As soon as I update of  EMUPATCH(Direct3D_CreateDevice*) possible.

**Comment by jarupxx** [comment]
CreateDevice has been fixed. It looks like Unknown parameter is valid pPresentationParameters.
Perhaps that EMUPATCH(D3DDevice_SetTextureState_BumpEnv_8), TexCoordIndex_4, SetTexture_4 are broken. Please do not merge.

**Comment by PatrickvL** [comment]
Smart placement of functions is absolutely important, but should be done as a separate pull request, with otherwise no functional change. And preferably at a point in time at which there are a low amount of branches across all forks (otherwise it'd be very hard to get all those rebased again)

**Comment by PatrickvL** [comment]
Is there anything else that needs to be done, or is this now ready to be merged?

**Comment by RadWolfie** [comment]
> By the way, Ninja gaiden title is working in debug build, but it **will crash instantly in release build**.

I don't see any new commits after his comment. Does that answer to your question @PatrickvL? 😛

Give him some time to fix what he needs to do.

**Comment by jarupxx** [comment]
Finish up for now. So ready to be merged.
How about we do it like this? Ninja gaiden title can be assigned different tasks @PatrickvL @RadWolfie.

**Comment by PatrickvL** [comment]
Could it be that the following regression report is due to the changes in OOVPA's? https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/1101#issuecomment-385229947

**Comment by jarupxx** [comment]
Just verify about 3 titles RalliSport, ExaSkeleton, Otogi. OOVPA will still be detected correctly.
Probably regression report couse by other issue.

**Pull request merged**
