### PR TITLE
Introduce D3D database v2

### PR DESCRIPTION
**Pull request by jarupxx**
Also verified D3DDeferredRenderState patchOffset for 3925 and 3948.

Verified with
Azurik - Rise of Perathia (3925)
Shikigami no Shiro (3948)
NightCaster (4039)
Double-S.T.E.A.L (4134)
NFL Blitz 2002 (4242)
Flight Academy (4361)
NCAA Football 03 (4432)
Jockey's Road (4531)
Innocent Tears (4627)
Tiger Woods PGA Tour 2003 (4721)
Whacked! (4831)
Medal Of Honor Frontline (4928)
Shikigami no Shiro Evolution (5028)
N.U.D.E.@ (5120)
C.A.T. Cyber Attack Team (5233)
Starsky And Hutch (5344)
NCAA Football 2004 (5455)
Top Spin (5558)
Midway Arcade Treasures (5659)
Digimon Battle Chronicle (5788)
Nickelodeon Tak 2 - The Staff of Dreams (5849)

### CODE REVIEW

**Comment by PatrickvL** [comment]
Great work!!!!

@RadWolfie Would you want the honor to verify this?

**Comment by RadWolfie** [comment]
Two things I would like to mention.
- `D3D8.1.0.5455.inl` file is missing new line. Github is reporting this error-ish. (easy fix)
- This PR is not on latest branch due to `DISABLED` has been renamed to `UNPATCHED`. Recommended action is to verify it is working and matching v1 database address to new v2 database. Then need to rename all `DISABLED` to `UNPATCHED` inside `D3D8.OOVPA.inl` file only before **rebase** merge into the branch.

I had not tested with the titles at the moment.

**Comment by RadWolfie** [comment]
Cel Damage title regress for "QuinCunx is unsupported (temporarily)". I had checked for any loss in HLE cache file. Nothing is lost, lots are marked as disabled, and some has new detection.

@PatrickvL, can you verify what's needed to work with current D3D? Or QuinCunx will be fixed in master branch for certain D3D function(s) will be unpatched?

New detection:
```
D3DDevice_GetLightEnable=20dc60
D3DDevice_SetRenderState_DoNotCullUncompressed=211aa0
D3DDevice_SetRenderState_RopZCmpAlwaysRead=211a60
D3DDevice_SetRenderState_RopZRead=211a80
D3DDevice_SetRenderState_StencilCullEnable=211a00
```
Disabled:
```
D3DDevice_CreateIndexBuffer
D3DDevice_CreateVertexBuffer
D3DDevice_GetDeviceCaps
D3DDevice_SetIndices
D3DDevice_SetRenderState_Deferred
D3DDevice_SetStateUP
D3DDevice_SetStateVB
D3DResource_GetType
D3DVertexBuffer_GetDesc
D3D_AllocContiguousMemory
D3D_CheckDeviceFormat
D3D_GetAdapterIdentifier
D3D_GetDeviceCaps
D3D_SetPushBufferSize
Direct3D_CheckDeviceMultiSampleType
XMETAL_StartPush
```

**Comment by PatrickvL** [comment]
The QuinCunx error can safely be changed into a EmuWarning

**Comment by PatrickvL** [comment]
What's more worrisome is the list of functions you mention under "disabled" - many of these should still be patched.

@jarupxx Did you test by cleaning the HLE cache first? That's a requirement, otherwise the scanning results from old OOVPA declarations would be used.

**Comment by RadWolfie** [comment]
Most titles will still regress due to my changes in DSound database in 3911. This is pretty much expected to happen. I am currently working on find CDirectSound_DownloadEffectsImage address in order to have IDirectSound_DownloadEffectsImage properly detected for 4039 and later revisions. (I already have 4039 supported which is not in the public branch at the moment. Turok Evolution won't run until I find the lowest revision for another minor change.)

Once I do have IDirectSound_DownloadEffectsImage properly detected for all XDK revisions. We can do re-verify to see if graphic is showing properly.

P.S. [4034] The Simpson Road Rage title is showing the graphic of vehicle, scenery, etc, except people,  5 out of 5 times. In fact, I do see Bart watching television (loading screen). I'll consider this as a halfway improvement. It does have some of those `disabled` names in HLE cache file. (The intro are still showing purple screen.)

DISABLED: ( [4034] The Simpson Road Rage )
```
D3DDevice_CreateVertexBuffer
D3DDevice_DeletePatch
D3DDevice_GetDeviceCaps
D3DDevice_SetIndices
D3DResource_GetType
D3D_CheckDeviceFormat
D3D_GetDeviceCaps
D3D_SetPushBufferSize
```

**Comment by PatrickvL** [comment]
Excuse me, but with DISABLED, do you mean those symbols aren't detected anymore?

**Comment by RadWolfie** [comment]
HLE cache v1 database shows without _DISABLED in it, yet it does shows with addresses (some doesn't have valid address, as in has value of zero). NOTE: D3D v1 database registrars DOES have `DISABLED` flag included. So @jarupxx is following base on v1 database currently have in this branch. Base on EmuD3D.cpp file, most of them are commented out.

The only functions are not commented out are: (from EmuD3D.cpp base on previous `DISABLED` functions mentioned above)
```
D3DDevice_SetRenderState_Deferred
D3DDevice_SetStateUP
D3DDevice_SetStateVB
XMETAL_StartPush
```

I do agree with emulation maintainers should decide which should have a patch or not. I'm just surprised it works fine with The Simpsons Road Rage title.

As for your question about DISABLED, I do not know if they are detected correctly. They are base on original v1 database hle cache file.

**Comment by jarupxx** [comment]
@PatrickvL Of course, I am cleaning the HLE cache before testing.

I agree, as the last category should ultimately be decided by emulation maintainers. Please tell us if you need a change category.

**Comment by RadWolfie** [comment]
@PatrickvL, beside `UNPATCHED` defined for some OOVPA registrars, any objection for this PR?

**Comment by PatrickvL** [comment]
No objections at all! I'm just very very glad you guys keep working on this!

**Pull request merged**
