### PR TITLE
Introduced D3D8LTCG database

### PR DESCRIPTION
**Pull request by jarupxx**
Now, lots of D3D8 patches have been unused. This database will be useful for the remaining PATCH. until improve GPU LLE over time.

### CODE REVIEW

**Comment by RadWolfie** [comment]
Hello @jarupxx We had some discussion on discord about HLE database. We're planning to separate HLE Database which will become as "symbol table" library to allow other xbox emulator/tools use it in their own application for research purpose. All the patches will be move into its own patch table internally.

**Comment by LukeUsher** [comment]
Amazing that this even works at all since LTCG can inline functions, change calling conversions etc as well as just change signatures... (I saw the screenshots on Discord, so I know it does at least somewhat work)

How do you plan to handle these cases? We may even need per-game patches for functions where calling conventions changed (hopefullly, none did :P)

**Comment by LukeUsher** [comment]
Let's see how this goes...

**Comment by jarupxx** [comment]
I have no plan for those functions... And who cares them ;)

**Pull request merged**
