### PR TITLE
D3d8to9 experimental

### PR DESCRIPTION
**Pull request by LukeUsher**
Requires EXTENSIVE testing before merging, creating this PR early so that it is easier for users to test.  (AppVeyor will build it!)

Please report and crashes/regressions as comments on this PR.

### CODE REVIEW

**Comment by CakeLancelot** [comment]
When going into game in Crimson Skies: High Road to Revenge I encounter an error that does not appear on the master branch:
image
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1791081/KrnlDebug.txt)

**Comment by zaykho** [comment]
I have tested multiple games, and 2 of them seems to have regressed (more info below).

---

### Game tested for d3d8to9 :  SM 1.3 ( 1e12f948 ) and  SM 3.0 ( 3e3b7059 )

`[ID- 49470018] (XDK- 4134)` Jet Set Radio Future - PAL
**`[ID- 494d000e] (XDK- 4721)` Panzer Dragoon Orta Demo - NTSC-US - OXM 13**
`[ID- 4d530015] (XDK- 4721)` Quantum Redshift - NTSC-US
`[ID- 4d530013] (XDK- 4831)` Blinx : The Time Sweeper - PAL
**`[ID- 4947002b] (XDK- 5028)` Panzer Dragoon Orta - PAL**
`[ID- 55530007] (XDK- 5455)` Ghost Recon : Island Thunder - NTSC-US
`[ID- 46530002] (XDK- 5455)` Otogi - PAL
`[ID- 00000000] (XDK- 5455)` Sonic Heroes E3 Demo - NTSC-US
`[ID- 41430014] (XDK- 5558)` XGRA - PAL
`[ID- 43430003] (XDK- 5558)` Dino Crisis 3 - NTSC-US
`[ID- 55530013] (XDK- 5659)` Rainbow Six 3 - PAL

---

_Here the kernel log of the 2 games that regressed :_ 

---

### Dumps : Cxbx-r Version 1e12f948 (Mar  7 2018)
_Pull request #976 - D3d8to9 experimental : Revert to original Pixel Shader model._

[KrnlDebug_pdodemo_SM1.3.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1791812/KrnlDebug_pdodemo_SM1.3.txt)
[KrnlDebug_pdo_SM1.3.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1791813/KrnlDebug_pdo_SM1.3.txt)

### Dumps : Cxbx-r Version 3e3b7059 (Mar  7 2018)
_Pull request #976 - D3d8to9 experimental : Use PixelShader Model 3.0_

[KrnlDebug_pdodemo_SM3.0.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1791819/KrnlDebug_pdodemo_SM3.0.txt)
[KrnlDebug_pdo_SM3.0.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1791820/KrnlDebug_pdo_SM3.0.txt)

---

_And here as a comparison with the latest master :_

---

### Dumps : Cxbx-r Version 830e82a7 (Mar  7 2018) Last Master

[KrnlDebug_pdodemo_lastmaster.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1790894/KrnlDebug_pdodemo_lastmaster.txt)
[KrnlDebug_pdo_last_master.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1790895/KrnlDebug_pdo_last_master.txt)

---

### Game reported in this test that have regressed

`[ID- 494d000e] (XDK- 4721)` Panzer Dragoon Orta Demo - NTSC-US - OXM 13
`[ID- 4947002b] (XDK- 5028)` Panzer Dragoon Orta - PAL

### Dumps : HLE Cache 

[Panzer Dragoon ORTA Demo-44fd35b7.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1790924/Panzer.Dragoon.ORTA.Demo-44fd35b7.txt)
[Panzer Dragoon ORTA-7230a3a6.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1790925/Panzer.Dragoon.ORTA-7230a3a6.txt)

### Dumps : XBE Info

[xbe_pdodemo.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1791834/xbe_pdodemo.txt)
[xbe_pdo.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1791832/xbe_pdo.txt)

---

### Status

Both the demo and the retail version of Panzer Dragoon Orta crash when entering a mission or a tutorial area with the : D3d8to9 : SM 1.3, while instead, with D3d8to9 : SM 3.0, both of them work without crashing (exactly like the master, but with worst graphics).

### Screenshot

_Here a screenshot of the demo version with D3d8to9 : SM 3.0 with a hacked resolution (used specifically to take this screenshot, all the xbe was tested without hacks)_
pdodemo_sm3 0

---

### Other results

The other games tested (that didn't regressed) got a better result at displaying various effects and graphical elements : 

**Ghost Recon : Island Thunder** from **master** to **3.0** to **1.3** : 

grit_master
grit_3 0
grit_1 3

**Jet Set Radio:  Future** from **3.0** to **1.3** : 

jsrf_3 0_a
jsrf_3 0_b
jsrf_1 3




_( All the test have been made with clear .xbe, no patch, no hack etc...... I have also completely wiped the appdata folder of cxbx-r and restarted the emulator for each game, to be sure that the result is accurate.)_

**Comment by LukeUsher** [comment]
Just a quick note: The PS 3.0 commit was reverted because Pixel Shaders designed for 1.3 won't work on later shader versions: So we actually ended up with no pixel shaders at all. (Or at least, every shader was replaced with a fake null shader), so test results on that specific commit are not valid. The other commits are good though.

**Comment by zaykho** [comment]
@LukeUsher Oh ok !

I didn't know that, so in the doubt, I tested both commit. This would also maybe explain why PDO was crashing in 1.3 but not in 3.0.

**Comment by zaykho** [comment]
With the new fix 55accd7e, both version of Panzer Dragoon Orta is now working as expected in the master !

**Comment by LukeUsher** [comment]
Overall response seems positive, many titles showing improvement, this can be a decent interim until we have proper support for DX9 or higher. 

Panzer Dragoon has some added instability, but this seems to be unrelated to this branch specifically, but an existing issue that is amplified by the changes, it will be investigated separately.

**Comment by ObiKKa** [comment]
zaykho, Can you please create issues for the _Island Thunder_ expansion and _XGRA_ as they don't exist yet?

**Comment by zaykho** [comment]
@ObiKKa Yes I will !

**Comment by CakeLancelot** [comment]
Crimson Skies High Road to Revenge works as before now.

**Pull request merged**
