### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Margen67**
Changed --recursive to --recurse-submodules since it's deprecated.
Formatting.
Fix small error in 'Fetching the code' section.
Removed screenshot gallery as it's now outdated.

### CODE REVIEW

**Comment by CakeLancelot** [comment]
So why is ``recursive`` depreciated? Is there difference in functionality between it and ``recurse-submodules``?

**Comment by Margen67** [comment]
@CakeLancelot https://stackoverflow.com/a/4438292
No.

**Comment by PatrickvL** [comment]
Thanks, but can't the readme be edited directly from our github front-page? Or does that require rights?

**Comment by Margen67** [comment]
@PatrickvL It requires rights. If I try to edit the readme it says this:
`You’re editing a file in a project you don’t have write access to. Submitting a change to this file will write it to a new branch in your fork Margen67/Cxbx-Reloaded, so you can send a pull request. `

**Comment by RadWolfie** [comment]
README.md is a file plus in a main git repo too. Hence the reason of rights to edit the files in the git repo. You do not see markdown files for Wiki in the main git repo. Conclusion: Wiki section is not handle by main git repo and separate permission system.

I thought you knew how github's GUI works. You must be using mobile third-party too much. 😛

**Pull request merged**
