### PR TITLE
Kernel thunks

### PR DESCRIPTION
**Pull request by ergo720**
This PR adds the remaining kernel thunks and fixes issue #64. These are only stubs though, all these functions still need an implementation.

### CODE REVIEW

**Comment by PatrickvL** [comment]
Nice work! Alas it's based on your other pr instead of master

**Comment by PatrickvL** [comment]
Maybe cherry pick it into a separate branch off upstream master, and PR that?

**Comment by ergo720** [comment]
Oops, I created the kernel thunk branch by cloning it from the Nt branch and so it has brought the other un-merged commits with it. I'll see what I can do about it.

**Comment by ergo720** [comment]
BTW, there is still one PANIC left, and it's the function/variable at offset 0, which is "undefined" so, afaik, that should be correct already

**Comment by PatrickvL** [comment]
True. So it can just be replaced by null and then the PANIC define can be removed

**Pull request merged**
