### PR TITLE
Kernel waitblock

### PR DESCRIPTION
**Pull request by PatrickvL**
I'd be interested to know if this kernel work causes regressions. If not, it'd be good the merge this in so the kernel test suite can progress further...

If there's still more to do, this pull request will be closed and reopened later

### CODE REVIEW

**Comment by hotzenplotz3000** [comment]
@PatrickvL
I've tested Silent Hill 4 and it shows a "dirty or damaged disk" message instead of playing the intro.
With current master it reaches the main menu and a bit further https://github.com/Cxbx-Reloaded/game-compatibility/issues/336

**debug build log**
[KrnlDebug_kernel_dbg.zip](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1790806/KrnlDebug_kernel_dbg.zip)

**Comment by zaykho** [comment]
So I have tested multiple games, and almost all of them regressed.

Here the kernel log of most of the games that regressed :

---

### Dumps : Cxbx-r 2e552d96 (Mar  7 2018) Kernel waitblock

[KrnlDebug_otogi_kernel_test.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1790880/KrnlDebug_otogi_kernel_test.txt)
[KrnlDebug_xgra_kerneltest.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1790883/KrnlDebug_xgra_kerneltest.txt)
[KrnlDebug_dc3_kerneltest.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1790886/KrnlDebug_dc3_kerneltest.txt)
[KrnlDebug_pdodemo_kerneltest.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1790887/KrnlDebug_pdodemo_kerneltest.txt)
[KrnlDebug_pdo_kerneltest.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1790888/KrnlDebug_pdo_kerneltest.txt)

---

And here as a comparison with the latest master :

---

### Dumps : Cxbx-r Version 830e82a7 (Mar  7 2018) Last Master

[KrnlDebug_otogi_last_master.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1790891/KrnlDebug_otogi_last_master.txt)
[KrnlDebug_xgra_lastmaster.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1790892/KrnlDebug_xgra_lastmaster.txt)
[KrnlDebug_dc3_lastmaster.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1790893/KrnlDebug_dc3_lastmaster.txt)
[KrnlDebug_pdodemo_lastmaster.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1790894/KrnlDebug_pdodemo_lastmaster.txt)
[KrnlDebug_pdo_last_master.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1790895/KrnlDebug_pdo_last_master.txt)

### Dumps : HLE Cache of the Last Master

[OTOGI-4016b85b.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1790920/OTOGI-4016b85b.txt)
[XGRA-12636441.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1790921/XGRA-12636441.txt)
[DINO CRISIS 3-9a07cede.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1790922/DINO.CRISIS.3-9a07cede.txt)
[Panzer Dragoon ORTA Demo-44fd35b7.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1790924/Panzer.Dragoon.ORTA.Demo-44fd35b7.txt)
[Panzer Dragoon ORTA-7230a3a6.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1790925/Panzer.Dragoon.ORTA-7230a3a6.txt)




---

### Game Reported in this test

`[ID - 46530002] (XDK - 5455)`Otogi - PAL
`[ID - 41430014] (XDK - 5558)`XGRA - PAL
`[ID - 43430003] (XDK - 5558)`Dino Crisis 3 - NTSC-US
`[ID - 494d000e] (XDK - 4721)`Panzer Dragoon Orta Demo - NTSC-US - OXM 13
`[ID - 4947002b] (XDK - 5028)`Panzer Dragoon Orta - PAL


---

### Status

Most of them simply crash or show a black screen without warning when booting, the only one that did passed the boot session was Otogi, but did still crash after the title screen (when the master crash just before starting to play on a map).


_( All the test have been made with clear .xbe, no patch, no hack etc...... I have also completely wiped the appdata folder of cxbx-r and restarted the emulator for each game, to be sure that the result is accurate.)_

[Download everything in one zip here.](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1790964/Kernel.waitblock.zip)

**Comment by PatrickvL** [comment]
Excellent report! Thank you very much!

**Comment by PatrickvL** [comment]
I'll investigate this all - until it's fixed, this PR stays closed

**Pull request closed without merging**
