### PR TITLE
Remove Any Experimental filesystem Linkage

### PR DESCRIPTION
**Pull request by RadWolfie**
Since AppVeyor CI's Visual Studio start making errors about experimental filesystem. Let's move on to use std filesystem than experimental version. After all, C++17 does have std filesystem implemented.

**EDIT:** And to replace `std::wstring_convert` to SDL's iconv library.

### CODE REVIEW

**Comment by RadWolfie** [comment]
Currently under investigation...

**Comment by RadWolfie** [comment]
http://www.unicode.org/faq//utf_bom.html#utf16-11
Hmm... I'm not sure if xbox is using UCS-2LE or UTF-8LE (not UTF-8) for wide character string in xbe's structure. Although, both does return the string correctly.

**Comment by LukeUsher** [comment]
> http://www.unicode.org/faq//utf_bom.html#utf16-11
> Hmm... I'm not sure if xbox is using UCS-2LE or UTF-8LE (not UTF-8) for wide character string in xbe's structure. Although, both does return the string correctly.

Xbox does not use UTF8-LE, it is using the exact same variant of UTF-16 as the standard Unicode Windows API on PC

**Comment by RadWolfie** [comment]
Whoops, it's a typo. I meant UTF16LE (without BOM). We can't use UTF-16 by itself due to decision maker inside SDL_iconv. If Cxbx-Reloaded is compiled with different architecture which use big endian then reading xbe's UTF-16LE (without BOM) string will be corrupted.

**Comment by gandalfthewhite19890404** [comment]
What is this - it caused by this PR?
image

**Comment by RadWolfie** [comment]
The message is from `src/core/kernel/support/EmuFile.cpp`, since MSVC's experimental filesystem was forwarded to official C++17 filesystem.

@gandalfthewhite19890404 I'm not able to reproduce your issue. Can you create a new issue with steps to reproduce a bug you found? Use the latest develop commit to reproduce the issue instead of this pull request's commit.

**Comment by LukeUsher** [comment]
I see that issue ocasionally: but it doesn't always have the same message.
It happens when std::filesystem is asked to delete a directory that is still in-use/locked.

**Comment by RadWolfie** [comment]
Base on discussion with @LukeUsher, the issue did not come from this pull request. Most likely cause is from third-party utility system application cause the directory to lock, prevent deletion, to output the error message.

**Pull request merged**
