### PR TITLE
4134

### PR DESCRIPTION
**Pull request by LukeUsher**
JSRF Now gets ingame, but is very broken graphically, still needs a lot of work before being playable.

image
image
image
image

### CODE REVIEW

**Comment by furrya** [comment]
Hmm. Now it's look much better from  time to time  on Windows 7 x64
screenshot_4

**Comment by LukeUsher** [comment]
Wow, hopefully we can get the vertex corruption issues solved pretty soon.

**Comment by LukeUsher** [comment]
What is the specification of the computer you got that result on? Graphics card, etc?

**Comment by furrya** [comment]
Windows 10 Professional 64 bit, 4 GGB RAm and Nvidia Geforcce 610 speces

**Comment by LukeUsher** [comment]
What about the Windows 7 specs?

**Comment by furrya** [comment]
@LukeUsher  Same. I have parallely two systems on the one PC

**Pull request merged**
