### PR TITLE
Implement LLE flags in place of LED text

### PR DESCRIPTION
**Pull request by Voxel9**
This PR addresses issue #1061.

My personal approach to this was to recursively scan through which LLE flags are active, then append the LLE flags string with "LLE-" followed by letters "A" "G" and "J" depending on which flags are checked. If no flags are active, the text "HLE" will be in place instead.
Of course, for now, APU and JIT flags are still disabled, but at least it's all future-proofed. :-)

HLE:
https://user-images.githubusercontent.com/16278868/40610575-da55410a-626a-11e8-8ed5-0e88e480d4b4.png

LLE-GPU active:
https://user-images.githubusercontent.com/16278868/40610576-dab64d74-626a-11e8-85e0-63c11765f951.png

LLE-GPU and LLE-JIT active:
https://user-images.githubusercontent.com/16278868/40610645-27c74096-626b-11e8-936e-c2e9bdb1b0e9.png

### CODE REVIEW

**Comment by jackchentwkh** [comment]
resource/Cxbx.aps shall be ignored, please remove it.

**Comment by Voxel9** [comment]
I don't think that's within my control to be able to delete files without submitting another PR. Unless there is a way?

**Comment by Voxel9** [comment]
I see a PR was made to remove it.... guys, if you'd have told me hw to do it, then I would have done it by myself lol....

**Comment by Voxel9** [comment]
I thought so. Cheers anyway

**Comment by RadWolfie** [comment]
Yeah, git is annoying whenever a file still existed when added to ignore list. Heh, beside it should be separate PR anyway. 😉

**Pull request merged**
