### PR TITLE
HACK: Add DSP hack for force failure to avoid access invalid pointer

### PR DESCRIPTION
**Pull request by RadWolfie**
With this hack, Otogi is able to progress further which is part of hidden bug.

### CODE REVIEW

**Comment by CookiePLMonster** [comment]
My suggestion would be to return failure only if `ppImageDesc` is non-NULL, because then it means the game might want to read the DSP program data back (e.g. PGR2 does it). In other cases it will probably not care, and so then it may be better to "lie" to the game IMO.

**Comment by PatrickvL** [comment]
Best also mention known test cases in code

**Comment by medievil1** [comment]
halo 2 MS-100 V1.03 boots further with this, plays the first video (though black screen) before hitting the pop up error

**Review by LukeUsher — CHANGES_REQUESTED** [review]
As per @CookiePLMonster's note: Only return E_FAIL when ppImageDesc is set.

When ppImageDesc is set to null, the games will not read back the program, and it's better to allow it to succeed.

**Comment by RadWolfie** [comment]
> As per @CookiePLMonster's note: Only return E_FAIL when ppImageDesc is set.
> 
> When ppImageDesc is set to null, the games will not read back the program, and it's better to allow it to succeed.

Base on our chat, Silent is assuming. I had not heard back about actual result for the difference. And I had not thoroughly check with internal functions to see if other parameters actually do write back to title's input pointers.

@PatrickvL I'll referred to ticket of titles affecting the issue.

**Comment by LukeUsher** [comment]
> > As per @CookiePLMonster's note: Only return E_FAIL when ppImageDesc is set.
> > When ppImageDesc is set to null, the games will not read back the program, and it's better to allow it to succeed.
> 
> Base on our chat, Silent is assuming. I had not heard back about actual result for the difference. And I had not thoroughly check with internal functions to see if other parameters actually do write back to title's input pointers. If other parameters do write back, we need to update them in some way with a successful return. Otherwise, it's pointless to return successful when nothing is set.
> 
> @PatrickvL I'll referred to ticket of titles affecting the issue.

Sure. There’s just a very height chance returning fail is what causes the regression mentioned above

**Comment by RadWolfie** [comment]
> And I have to call it a regression, SW Jedi knight, no audio after the initial video's at all now... before it was just other characters being so low you could not hear them, now it is complete silence...

Yeah, it needs some investigation. Although main purpose of this pull request is to allow titles progress further than trying to access data from non-existence pointer which can affect other contributors investigate unrelative issue to this. DSP isn't my field of expertise.

**Comment by RadWolfie** [comment]
Closing as there's no one willing to test either solution nor have time to reverse engineer internal functions relative to patches in this pull request.

**Pull request closed without merging**
