### PR TITLE
HLEDataBase maintenance

### PR DESCRIPTION
**Pull request by jarupxx**
Removes Comment outed REGISTER_OOVPAS and invalid OOVPA In XAPILIB.
This one related to Issue #798

### CODE REVIEW

**Comment by PatrickvL** [comment]
Great work!

I did notice you kept `OOVPA_XREF(CDirectSound_EnableHeadphones, 3911, 7,`... why?

**Comment by PatrickvL** [comment]
In Xapi.1.0.3911.inl, `OOVPA_NO_XREF(ReadFileEx, 3911, 8)` and `OOVPA_NO_XREF(WriteFileEx, 3911, 8)` are deleted, why?

**Comment by PatrickvL** [comment]
In `OOVPA_XREF(D3DDevice_SetStreamSource, 4034, 1+14` you removed a few OV-pairs - why?

**Comment by PatrickvL** [comment]
The previously disabled `OOVPA_NO_XREF(D3DDevice_BeginStateBlock, 3925, 6)` didn't have a "moved" comment, but a `Use XREF` comment - if that was meant as a TODO, it should be kept, until either : the TODO is done, _or_ it's been determined the entire OOVPA should still be deleted...

**Comment by PatrickvL** [comment]
That's all I could find ;) I hope these review comments help you with the last few finishing touches.

All-in-all you've done a great job, so many removals ... well done!

**Comment by jarupxx** [comment]
Thank you for your review :)

In ```D3DDevice_SetStreamSource, 4034```. It seems that it came from WIP_LessVertexPatching. I speculated you do not like 28 Offset-Pairs. I think the current Offset-Pairs is good, what do you think?

In ```D3DDevice_BeginStateBlock, 3925``` is merged into ```D3DDevice_BeginStateBlock, 3911``` which added XREF plus moved to D3D8.1.0.3911.inl. So we will remove it.

**Comment by PatrickvL** [comment]
For  `D3DDevice_SetStreamSource` : if I remember correctly, I added these additional OV-pairs to strengthen this OOVPA, but didn't enable them yet in fear of damaging re-use in higher XDK versions.
If we ever need to strengthen OOVPA, we'll do it when needed. For now, it's fine - keep it nice and clean.

Thanks for explaining the removal of `D3DDevice_BeginStateBlock`, and good luck on the other remarks.

**Comment by PatrickvL** [comment]
Oops! Only after merging I noticed you didn't restore `OOVPA_NO_XREF(CloseHandle, 3911, 8)` yet - if that's an important one, submit a new pull-request, in a new branch, please (because I've heard that after merge, extending a branch could create problems).

**Comment by jarupxx** [comment]
Ah! I will restore the CloseHandle.

**Pull request merged**
