### PR TITLE
Delete .travis.yml

### PR DESCRIPTION
**Pull request by Margen67**
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

### CODE REVIEW

**Comment by GXTX** [comment]
I still disagree keeping them all around - however this change only effects macOS runners, not Windows or Linux.

```
The upcoming pricing change will not affect those of you who are:

    Building on the Travis CI 1, 2 and 5 concurrency job plans who are building on Linux, Windows and experimental FreeBSD environments.
```

Unless I'm missing something?

**Comment by Margen67** [comment]
> 
> 
> I still disagree keeping them all around - however this change only effects macOS runners, not Windows or Linux.
> 
> ```
> The upcoming pricing change will not affect those of you who are:
> 
>     Building on the Travis CI 1, 2 and 5 concurrency job plans who are building on Linux, Windows and experimental FreeBSD environments.
> ```
> 
> Unless I'm missing something?

It doesn't support VS2019 or allow artifacts to be downloaded so it's even more useless than the others.

**Comment by GXTX** [comment]
Like I said, I agree with removing everything and just sticking with GitHubs CI. I just don't think the change they're doing is relevant?

**Comment by Margen67** [comment]
> 
> 
> Like I said, I agree with removing everything and just sticking with GitHubs CI. I just don't think the change they're doing is relevant?

https://twitter.com/james_hilliard/status/1336081776691843072

**Comment by GXTX** [comment]
Thanks for that, I'm not sure why I read the post wrong? Something I'm still confused about, I thought there was a difference between travis-ci dot com and dot org - with one of them being the one which offered the free service.

**Comment by RadWolfie** [comment]
> Thanks for that, I'm not sure why I read the post wrong? Something I'm still confused about, I thought there was a difference between travis-ci dot com and dot org - with one of them being the one which offered the free service.

Off topic, though I'll reflect this confusion to links for clarification:
 - [Question about difference between org and com domain.](https://devops.stackexchange.com/questions/1201/whats-the-difference-between-travis-ci-org-and-travis-ci-com)
 - [Newsletter about org domain will be shutdown (transfer to com domain).](https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom)

**Comment by RadWolfie** [comment]
I made my final decision. Once their migration and moved their service to com domain, let's have this pull request merge afterward. Since it is pointless to have 10-15 minutes job per commit/pulled to fork repo for each job with risk of losing big credits from anyone's account.

**Comment by RadWolfie** [comment]
Converted to draft since Travis CI's org site is still active.

**Comment by Margen67** [comment]
image

**Review by RadWolfie — APPROVED** [review]

**Pull request merged**
