### PR TITLE
Added Patreon link

### PR DESCRIPTION
**Pull request by TotalCaesar659**

### CODE REVIEW

**Comment by LukeUsher** [comment]
I'm not sure about this, mainly because the patron is my personal patreon, it's contributing to fund my development of the emulator, and not other contributors. 

I think merging this will be unfair to the other devs. I try to make it clear that this Patreon funds myself to work on the Cxbx-Reloaded rather than directly funding the project, and this pull-requests doesn't take this fact into account. 

Thanks for the contribution anyway!

**Comment by TotalCaesar659** [comment]
I didn't even know about this Patreon before I've found the link accidentally on another site, so I've thought that is a mistake. Don't consider it as disrespectful for you or other developers.

**Comment by PatrickvL** [comment]
An understandable oversight. No offense taken. But like Luke said: it's better to be precise about this. Other contributors like myself have no patreon. Luke talked about this beforehand, it's no big deal to me. If it helps, it helps right?!

**Comment by RadWolfie** [comment]
With the current change @TotalCaesar659  have right now is quite bit misleading. If you do make it more clearly to explain it is for @LukeUsher to make some improvement for Cxbx-Reloaded, then it shall be fine knowing what's the patreon link is for. Plus stating there are other contributors helping out to get it more stable-ish.

@LukeUsher
Personally, I think it's harder to get notice of patreon donation out in public if you don't include it in the readme file or on a wiki page.

**Comment by LukeUsher** [comment]
So what should we do with this then? Merge it, ask for working to be changed/added clarity to the purpose of the Patreon/close without merging?

I'll leave it to a vote among other contributors.

**Comment by PatrickvL** [comment]
Change the wording so it's clear is a personal patreon, and merge that

**Comment by RadWolfie** [comment]
Ask for working to be change.

**Comment by PatrickvL** [comment]
This PR was open for far too long. I've reworded it a little, and merged it in. @TotalCaesar659 Thanks for your involvement

**Pull request merged**
