### PR TITLE
Build chain improvements

### PR DESCRIPTION
**Pull request by x1nixmzeng**
The old build chain had a few issues:

* The pre-build event to generate a version header would touch `Version.h` to write the git hash. This was bad because any files which included it needed to be recompiled!

* We called `Export.bat` after the build, which would gather all the files and ZIP them up! This took a few seconds!

To solve this I've made sure `Version.h` is only updated if the git hash is updated. I've also made sure only Appveyor will package files - see `AppveyorPackager.ps1` (although this is untested).

### CODE REVIEW

**Comment by PatrickvL** [comment]
This is a very welcome change! Only, why does the AppVeyor build fail?

**Comment by PatrickvL** [comment]
Thank you - beautifully done! I have no further remarks. Please tell if you want to add anything else.
Once we know you're done, this will be merged ASAP.
Thanks again

**Comment by LukeUsher** [comment]
Thanks for doing this!

**Comment by x1nixmzeng** [comment]
No worries! All that's left is the artifact mask - instead of the export folder, only the zip files!

**Comment by x1nixmzeng** [comment]
It's ready to be merged!

**Comment by LukeUsher** [comment]
Great work

**Pull request merged**
